Jigsaw-Code/outline-apps

cordova-plugin-outline/apple/vpn/PacketTunnelProvider.h
Hmm, think I forgot to `git push` this when merging https://github.com/Jigsaw-Code/outline-client/pull/23.
=> fix formatting

apple/xcode/ios/Outline/Outline-Info.plist, apple/xcode/ios/Outline/VpnExtension-Info.plist, apple/xcode/osx/Outline/Outline-Info.plist, apple/xcode/osx/Outline/VpnExtension-Info.plist, config.xml
* Android v1.0.2
* iOS/macOS v1.0.1
=> Release Android and Apple clients

www/app/app.ts, www/app/settings.ts, www/messages/en.json, www/messages/es.json, www/ui_components/servers-view.html
* Display a notification to explain the auto-connect feature behavior.
* In Windows, displays the auto-connect notification on the next connection attempt if the user has dismissed/ack'ed the non-system VPN warning.
=> Auto-connect UI

.gitattributes, electron/connection_store.ts, electron/index.ts, electron/run_action.sh, www/app/windows_connection.ts
* Automatically starts the proxy on startup if the it was connected at shutdown. 
* Persists the last successful connection configuration to disk and clears it upon disconnection.
* Only checks for updates in non-debug builds.
=> Windows auto-connect

electron/index.ts, electron/process_manager.ts, electron/sentry_logger.ts
* Fixes a bug that would throw a `ConfigureSystemProxyFailure` for all connection failures.
* Enables Sentry breadcrumb logging in the Electron process.
* Increases the number of stored breadcrumbs to 100.
=> Windows: improve native error handling

.travis.yml, config.xml
* Bumps the Android version for release.
* Reverts #169.
* Fixes the Travis deployment pattern.
=> Release Android v1.1.4

electron/index.ts
* Shows the app window when a second instance of the app is launched.
* Focuses the app window when the tray icon is clicked and the window is not visible.
=> Refine window behavior on second instance and tray interaction

package.json
This is a pretty major release; bumping semver minor number for "new features".
=> bump version number for next windows release

electron/routing_service.ts
This keeps coming up on my client...
=> some lint fixes

www/types/sudo-prompt.d.ts
Dammit, merged https://github.com/Jigsaw-Code/outline-client/pull/218 before uploading this comment.
=> explain sudo-prompt error type

electron/routing_service.ts, www/types/sudo-prompt.d.ts
Dammit, this thing is so weird.
=> sudoError is sometimes not a string

cordova-plugin-outline/android/java/org/outline/shadowsocks/Shadowsocks.java, cordova-plugin-outline/apple/vpn/Shadowsocks.m, electron/process_manager.ts
Addresses the client side of https://github.com/Jigsaw-Code/outline-server/issues/85
=> Increase ss-local timeout to INT_MAX

electron/index.ts
* Uses `NativeImage` instead of image paths to `.ico` files to build the tray icons to fix the following error:
``` typescript
TypeError (Error processing argument at index 0, conversion failure from C:\Program Files (x86)\Outline\resources\app.asar\icons\win\icon.ico)
```
* See [this issue](https://github.com/electron/electron/issues/7657) for context.
=> Use electron.NativeImage for tray icons

cordova-plugin-outline/android/java/org/outline/vpn/VpnTunnelService.java
Creates a notification channel for Android versions greater than O.
=> Fix notifications for Android >O

electron/beta_migration.ts, electron/build_action.sh, electron/index.ts, electron/package_action.sh, electron/release_action.sh, package.json, www/types/fs-extra.d.ts, www/ui_components/licenses/licenses.txt, yarn.lock
Thanks for prodding me to do this. Pretty easy in the end, tested on Win 7/8/10.
=> automatically migrate server list when updating off of beta

cordova-plugin-outline/android/java/org/outline/vpn/VpnTunnelService.java
* In Android 8+, a service must call `startForeground` 5 seconds after it has been started via `Context.startForegroundService`. Otherwise, the system throws a `RemoteServiceException` and flags it as an ANR.
* This change calls `startForeground` in the VPN service's auto-connect logic, as soon as the connection configuration is retrieved from storage.
* Improves the robustness of the notification to ensure that `startForeground` is always called.
=> Android: start foreground service, improve robustness

src/electron/process_manager.ts
A little thing to try to reduce the frequency of failed connection events: inspect the TAP device config before connecting, and fail (with "unexpected error") if it's not what we want. Regarding auto-connect, the assumption here is that if the system is in an unsupported state then all bets are off - WDYT?
=> test TAP device config before trying to connect

resources/master_messages.json
=> Replace hyphens with underscores in message keys

src/electron/add_tap_device.bat
This also fixed #291 for me.
Sample before this fix,
outlineinstaller-tap-devices-before.txt
```
NetConnectionID=test
NetConnectionID=
NetConnectionID=
NetConnectionID=本地连接 12
NetConnectionID=
```
outlineinstaller-tap-devices-after.txt
```
NetConnectionID=test
NetConnectionID=
NetConnectionID=
NetConnectionID=本地连接 12
NetConnectionID=
NetConnectionID=本地连接 13
NetConnectionID=
```
=> remove empty NetConnectionID

cordova-plugin-outline/android/resources/strings/values/strings.xml
=> Android: add missing string to default locale

cordova-plugin-outline/apple/src/OutlineSentryLogger.swift
* We relied on CocoaLumberjack's `DDFileLogger` to retrieve the sorted file list of VpnExtension logs in order to add them to Sentry.
* Since updating to CocoaLumberjack v3.4.2 (latest), reading the VPN extension logs is broken -`DDFileLogger.logFileManager.sortedLogFileInfos` returns `[]` when there are files at the logs directory.
* This change replaces `DDFileLogger` with the default `FileManager` in order to enumerate the VpnExtension's log files.
* Adds logic to submit a balanced number of logs from the VpnExtension and the app processes, while maximizing the number of breadcrumbs sent.
=> Apple: fix VpnExtension logs submission

src/electron/add_tap_device.bat
Further polish - I've seen several failures I suspect are related to this.
=> fail if cannot fetch network device list, handle %tmp% with spaces

src/electron/add_tap_device.bat
@lgg FYI this is the timeout weirdness I mentioned in https://github.com/Jigsaw-Code/outline-client/pull/413#issuecomment-443859903 - it will make your timeout actually have effect!
=> use waitfor rather than timeout

src/electron/linux/build_action.sh, src/electron/linux/package_action.sh, src/electron/routing_service.ts, src/electron/util.ts
Ran into a couple of issues on Windows, previously reported here:
https://github.com/Jigsaw-Code/outline-client/issues/435
This seems to work around it, and a few random tidy-ups.
=> fix a few issues with the new linux stuff, get windows running again

.travis.yml, scripts/environment_json.sh, src/electron/linux/package_action.sh
Mostly I just copied the config from the server manager for Linux.
=> mark linux client beta, add to daily builds

tools/outline_proxy_controller/CMakeLists.txt, tools/outline_proxy_controller/init/outline_proxy_controller.service, tools/outline_proxy_controller/logger.cpp, tools/outline_proxy_controller/logger.h, tools/outline_proxy_controller/outline_controller_server.cpp, tools/outline_proxy_controller/outline_controller_server.h, tools/outline_proxy_controller/outline_daemon.cpp, tools/outline_proxy_controller/outline_proxy_controller.cpp, tools/outline_proxy_controller/outline_proxy_controller.h
Just a few more things. @AurangZ FYI
=> linux client cleanup and copyright headers

package.json, src/electron/routing_service.ts, src/www/app/clipboard.ts, src/www/app/persistent_server.ts, src/www/app/settings.spec.ts, src/www/app/updater.ts, src/www/app/windows_connection.ts, yarn.lock
Random code health exercise for the day.
Main breakage was 2.7's (!) "Strict Class Initialization":
https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-7.html
=> move to typescript 3.1

scripts/semantic_version.sh
Just noticed this broken on daily builds.
=> fix semantic version for daily electron client builds

apple/xcode/osx/Outline/Outline-Info.plist, apple/xcode/osx/Outline/VpnExtension-Info.plist
=> bump macos version numbers for release 1.2.4

package.json, yarn.lock
I don't see any major new features, just staying up to date. Seems to work fine for us without any changes to code.
=> update to latest sentry

package.json, yarn.lock
Seems to work without any changes on our side.
=> update to electron-promise-ipc 1.x

src/electron/add_tap_device.bat
Fixes:
https://github.com/Jigsaw-Code/outline-client/issues/278
=> append some common directories to the PATH

src/electron/custom_install_steps.nsh
Main thing here is to skip the Sentry failure report when the user does not accept to install the driver. Tested on Windows 7.
=> handle when the user does not trust the TAP device driver

src/electron/connectivity.ts, src/electron/index.ts, src/electron/process_manager.ts
Planning some major work to `process_manager.ts` and one obstacle is this connectivity and reachability-related code scattered throughout; this PR moves all that to a separate file.
=> factor out connectivity and reachability functions from process management code

gulpfile.js, package.json, yarn.lock
=> a couple of simplifcations to our Gulpfile

apple/xcode/ios/Outline/Outline-Info.plist, apple/xcode/ios/Outline/VpnExtension-Info.plist
=> bump version numbers for ios v1.2.6

cordova-plugin-outline/apple/vpn/PacketTunnelProvider.m
The goal of this PR is to mitigate "wakeup crashes" that happen when we perform excessive network activity on network changes. We have seen multiple network change events fire since iOS 11 when connecting over WiFi. While this behavior is not 100% reproducible, I have not been able to reproduce it with these change. The concrete improvements include:
* Moving the network path comparison out of `handleNetworkChange`. I suspect the repeated network change events may have to do with the timing of the `observeValueForKeyPath` method.
* Comparing the string descriptions of the network paths. If the issue manifests, this should guarantee an early return to avoid network activity. Additionally, "real" network changes follow a sequence where the `path.status` transitions from `unsatisfied` to …
=> Improve Apple network change detection robustness

src/electron/index.ts
Unrelated to my recent big PR, I think, but an easy fix: clear the connection store when the user explicitly clicks QUIT - currently if they do this while connected and restart the system, Outline will reconnect on next start.
=> clear connection store on quit

src/www/app/main.ts, src/www/app/persistent_server.ts, src/www/ui_components/server-card.html, src/www/ui_components/server-list.html
There's a drive-by small improvement to type safety
=> Display the port number for each server

third_party/go-tun2socks/LICENSE, third_party/go-tun2socks/METADATA
* Adds LICENSE and METADATA files to go-tun2socks.
=> go-tun2socks third_party compliance

cordova-plugin-outline/android/java/org/outline/vpn/VpnTunnelService.java
Fixes a bug that would prevent the UI from receiving the connection start broadcast for Shadowsocks start failures.
=> Android: fix connection start bug

config.xml
Bumps version and build number.
=> Release Android client v1.2.12

README.md
Updates the README with the latest build, run, and package instructions for Windows and Linux.
=> Update Electron build instructions

README.md, src/electron/index.ts, tools/build/build.sh
- Merges master at 7b61aaa into `go-tun2socks`. 
- No merge conflicts detected. No new code added.
=> Merge master

config.xml
Version code increase accounts for releases in the `go-tun2socks` branch.
=> Increase Android version

config.xml
=> Increase Android version to v1.4.0 (32)

apple/xcode/ios/Outline/Outline-Info.plist, apple/xcode/ios/Outline/VpnExtension-Info.plist, apple/xcode/osx/Outline/Outline-Info.plist, apple/xcode/osx/Outline/VpnExtension-Info.plist, config.xml
- Beta release for Android.
- Prod release for iOS and macOS.
=> Increase Android and Apple versions to 2.0.0

src/electron/build_action.sh, src/electron/electron_main.webpack.js
Migrates the electron main process compilation to webpack.
=> Build electron main process with webpack

resources/original_messages.json, src/electron/index.ts, src/www/messages/en.json
With this PR, we create the Window only once. No need to keep recreating it. It makes it easier to maintain.
This also fixes https://github.com/Jigsaw-Code/outline-client/issues/860 by adding a "Open" option to the tray menu on Linux.
=> Simplify window behavior

cordova-plugin-outline/android/java/org/outline/vpn/VpnTunnelService.java
=> Fix null pointer exception in VPN connectivity broadcast

src/www/app/outline_server.spec.ts
Adds unit tests for `OutlineServerRepository`.
=> Server repository unit tests

tools/smartdnsblock/smartdnsblock/smartdnsblock.cpp
The buffer allocated to adaptersAddresses may be less than the adaptersAddresses actually need, so the first call may fail with ERROR_BUFFER_OVERFLOW(111). Since the _sizeParameter_ in GetAdapterAddresses() function can return with a required value after the first call, one more time to call GetAdaptersAddresses() may figure out this problem.
reference link: https://docs.microsoft.com/en-us/windows/win32/api/iphlpapi/nf-iphlpapi-getadaptersaddresses
=> Windows: an unexpected error occurred reports (#994)

src/electron/go_vpn_tunnel.ts
- Restarts the Go tun2socks process when it exits without the user disconnecting.
- Windows: preemptively stops the tun2socks process on suspend, so as not to trigger the restart logic.
=> Electron Go: restart the tun2socks process when it crashes

src/www/base.webpack.js
- Preserves class and function names during TS/JS code minimization in order to enable more accurate debugging in error reports.
- Other minimization settings remain the same, since webpack uses `TerserPlugin` with a default configuration in production mode.
=> Keep class and function names during minimization

resources/original_messages.json, scripts/l10n/validate_localized_keys.py, src/www/messages/en.json, src/www/ui_components/about-view.js
=> Update about text

.github/workflows/build_and_test.yml, tools/build/build.sh
Ah, I accidentally forgot to change the base branch before merging this the first time.
Also, we need to change the branch protection rules.
---
--> Blocks https://github.com/Jigsaw-Code/outline-client/pull/1109
=> CI build for Linux, Windows, MacOS and Android (master)

src/www/ui_components/servers-view.js
ZERO_STATE is not a valid state.
Before:
After:
=> Fix zero state

scripts/test.action.sh, src/www/app/app.ts, src/www/model/server.ts, src/www/ui_components/app-root.js, src/www/ui_components/server_list.ts, src/www/ui_components/servers-view.js
This fixes the server list data binding. Now all the UI changes are made via the ui model. No more modifying the dom directly.
This should help make the drag and drop work.
=> Fix server list data binding

cordova-plugin-outline/android/java/org/outline/vpn/VpnTunnel.java
=> Mark Outline connections as not metered

.github/workflows/build_release_candidates.yml
Instead of picking and choosing what we upload, let's just grab everything.
=> fix(release): upload the entire rc build artifact

src/www/views/servers_view/index.ts
I missed a server indicator on the empty state screen...
=> fix(ui): missed an indicator

src/www/app/app.ts, src/www/app/electron_main.ts, src/www/app/electron_outline_tunnel.ts, src/www/app/main.ts, src/www/app/platform.ts, src/www/model/errors.ts
This is a purely re-formatting PR which is a prerequisite for feature PR #1274 . I did not touch other files to reduce the noise and prevent any potential merge conflicts.
=> 🎨 style(app): prettier format code files of #1274

list.action.mjs, scripts/run_action.mjs
=> chore(devtools): outline letterhead

docs/apple_development.md
I'm also grouping by platform, as it makes it easier to follow when developing.
=> chore(docs): fix Apple documentation

.eslintrc.json, package-lock.json, package.json
=> feat(devtools): eslint compat

src/www/ui_components/app-root.js
This is a pure re-formatting change-list. The main purpose of this PR is to further reduce some noises in #1323 .
=> style(www): 🎨 format app-root.js

src/cordova/apple/xcode/ios/Outline/Outline-Info.plist, src/www/ui_components/about-view.js, src/www/ui_components/app-root.js, src/www/ui_components/language-view.js, src/www/ui_components/privacy-view.js, src/www/views/servers_view/server_list_item/server_card/index.ts
fixes ios layout by removing min-width from server card (ideally it should be driven by `calc` but would require more refactoring)
fixes font issue by explicitly using the font family in all the views (sorry, i just forgot to do that lol)
the submit form can be repro'd in production, so we can fix that when we migrate it to lit (there's quite a few bugs like this)
=> fix: breaking ios issues and update ios version

src/www/style.css, src/www/views/servers_view/index.ts, src/www/views/servers_view/server_connection_indicator/index.ts, src/www/views/servers_view/server_list_item/server_card/index.ts
=> fix(www): empty name, body inset, list padding

src/www/app/app.ts
This stops the user from spamming the connect/disconnect button, potentially causing a race condition
=> fix(www): adds basic server connection toggle timeouts

src/electron/build.action.mjs, src/electron/get_electron_build_parameters.mjs
example command:
```
electron/build linux -- --release --publish='{"provider":"generic","url":"https://my.cool.repository.com/"}'
```
=> fix(devtools): add publish config url so we can get proper client updates

src/www/app/outline_server_repository/access_key_serialization.ts, src/www/app/outline_server_repository/server.ts, src/www/model/errors.ts, src/www/views/servers_view/server_list_item/server_card/index.ts
Also addresses the lack of spacing in the android card
=> feat(www): dynamic key text body support

src/cordova/plugin/apple/vpn/PacketTunnelProvider.m
Fix for Issue https://github.com/Jigsaw-Code/outline-client/issues/1489
(can't establish connection due to crash in VpnExtension)
=> fix(cordova/apple): update PacketTunnelProvider.m

config.xml, src/build/get_version.mjs, src/cordova/apple/xcode/ios/Outline/Outline-Info.plist, src/cordova/apple/xcode/ios/Outline/VpnExtension-Info.plist, src/cordova/apple/xcode/macos/Outline/Outline-Info.plist, src/cordova/apple/xcode/macos/Outline/VpnExtension-Info.plist
- fix: temporarily remove client feedback view: #1548 , #1569 
- fix: ssconf:// deeplinking on ios: #1524
- fix: spurious typescript errors: #1550
- feat(www): 🌐 support 11 more languages: #1566
- chore: ⏫ upgrade tun2socks library to v3.1.0: #1576
=> chore: 🎉 release v1.10.0 for all platforms

src/electron/electron-builder.json, src/electron/index.ts
I was able to confirm the fix on Linux. There's still more breakage to fix.
=> fix(client/electron): fix tray icon

server_manager/web_app/test.action.sh
The path was broken in the refactoring.
=> fix(manager): fix Karma test for server_manager

.eslintrc.json, client/electron/preload.ts, client/electron/process.ts, client/electron/routing_service.ts, client/src/www/app/electron_main.ts, client/src/www/app/electron_outline_tunnel.ts, client/src/www/app/fake_tunnel.ts, client/src/www/app/outline_server_repository/index.ts, client/src/www/app/outline_server_repository/server.ts, client/src/www/app/vpn_installer.ts, client/src/www/model/errors.ts, client/src/www/model/events.ts, infrastructure/path_api.ts, infrastructure/timeout_promise.ts, server_manager/model/digitalocean.ts, server_manager/model/gcp.ts, server_manager/model/location.ts
Following the TS style guide: https://google.github.io/styleguide/tsguide.html#visibility
=> chore: add lint rule to prevent unnecessary `public` modifiers

client/src/cordova/plugin/README.md
PR #1945 moved the location of the pbxproj files. This PR adjusts sources to changes.
=> fix(docs): update pbxproj files

client/src/cordova/android/OutlineAndroidLib/outline/src/main/aidl/org/outline/IVpnTunnelService.aidl, client/src/cordova/android/OutlineAndroidLib/outline/src/main/java/org/outline/vpn/VpnTunnelService.java, client/src/cordova/plugin/android/java/org/outline/OutlinePlugin.java
Creating one commit from PR https://github.com/jigsaw-Code/outline-apps/pull/2099 to get around the CLA issue. 
I've set the email to 68923563+62w71st@users.noreply.github.com in this PR. 
Tested again with Android Studio and checking logs.
=> refactor(client/android): remove dependency on tunnel config for serverName

client/src/www/style.css, client/src/www/views/root_view/privacy_acknowledgement_dialog/index.ts
Follow-up to #2139 to fix some styling. Before and after screenshots below:
=> fix(client): fix styling of the splash screen

server_manager/www/app.ts, server_manager/www/ui_components/app-root.ts, server_manager/www/ui_components/outline-share-dialog.ts
These code paths are all unused.
=> chore(manager): delete dead S3 invite code

server_manager/README.md, server_manager/base.webpack.js, server_manager/electron/build.action.sh, server_manager/electron/package.action.sh, server_manager/electron/start.action.sh, server_manager/electron_main.webpack.mjs, server_manager/electron_preload.webpack.mjs, server_manager/test.action.sh, server_manager/www/build.action.sh, server_manager/www/build_install_script.action.sh, server_manager/www/start.action.sh, server_manager/www/test.action.sh
This reverts commit ba59dd46a8885bb89ff2aced73502ea0c7b2e323.
=> Revert "refactor(manager): output folder cleanup (#2083)"

client/README.md
=> docs(client): update required Go to 1.21

client/go/outline/neterrors/neterrors.go
Commit 341e6d70b2c76c15dc8cf301bf14a954b23b6a1b moved the location of the `errors.ts` file. This PR adjusts sources to changes.
=> fix(docs): update `errors.ts` reference

client/go/outline/config/config_shadowsocks.go, go.mod, go.sum
Depends on https://github.com/Jigsaw-Code/outline-sdk/pull/370
=> feat(client): support Shadowsocks prefix for UDP

client/electron/index.ts
Fixes #2434, a large source of Sentry errors (3.2m in the last 30d).
=> fix(client/windows): properly handle Electron auto-updater errors

package-lock.json, server_manager/www/ui_components/app-root.ts
Fix/suppress the following new lint errors
```
npx gts lint server_manager/www/ui_components/app-root.ts
version: 18
[...]/outline-apps/server_manager/www/ui_components/app-root.ts
827:14  error  'e' is defined but never used                                                                                                                                       @typescript-eslint/no-unused-vars
841:38  error  The `Function` type accepts any function-like value.
Prefer explicitly defining any function parameters and return type                                             @typescript-eslint/no-unsafe-function-type
851:45  error  The `Function` type accepts any function-like value.
Prefer explicitly defining any function parameters and return type …
```
=> chore: fix/suppress lint errors

.github/workflows/build_and_test_debug_client.yml
See https://github.com/actions/runner-images/issues/11101
=> chore(devtools): update runners from deprecated images

.github/workflows/build_and_test_debug_client.yml
=> ci(client/windows): increase CI timeout

.github/workflows/build_and_test_debug_client.yml, client/electron/go_helpers.ts, client/electron/go_vpn_tunnel.ts, client/electron/index.ts, client/electron/vpn_service.ts, client/go/outline/client.go, client/go/outline/client_test.go, client/go/outline/electron/main.go, client/go/outline/method_channel.go, client/go/outline/parse.go, client/go/outline/parse_test.go, client/go/outline/vpn_linux.go, client/src/www/app/outline_server_repository/config.ts, client/src/www/app/outline_server_repository/server.ts, client/src/www/app/outline_server_repository/vpn.cordova.ts, client/src/www/app/outline_server_repository/vpn.ts
This creates space for the reporter logic and other future logic.
/cc @62w71st @emohandesi
=> chore(client): encapsulate client config

client/src/www/app/app.ts
=> feat(client): turn on dark mode

client/go/outline/connectivity/connectivity.go, client/go/outline/connectivity/connectivity_net_test.go, client/go/outline/connectivity/connectivity_test.go
Fixes https://github.com/Jigsaw-Code/outline-apps/issues/2326 and https://github.com/Jigsaw-Code/outline-apps/issues/2561
=> feat(client): make connectivity test more robust
