Jigsaw-Code/outline-apps

electron/index.ts
package.json
www/app/electron_main.ts
yarn.lock

Use the new Sentry for Electron:
https://blog.sentry.io/2018/03/13/introudcing-sentry-electron
I started this originally hoping to get sourcemaps working but that seems to be more involved than I'd like, regardless of which Sentry library we use. However, I like the simplified API (no need to reset the user context after feedback submission, for example) so I think it's probably better overall.

use sentry for electron

---

.travis.yml

* Removes `$APPLE_CREDENTIALS_CI_USER_TOKEN`, since it is the same as `$CI_USER_TOKEN`.
* Moves `$FASTLANE_PASSWORD` and `$MATCH_PASSWORD` to the global environment, as they are needed by the package and ios stages.

Fix Travis iOS package stage

---

electron/build_action.sh
electron/package_action.sh
electron/process_manager.ts

My bad, I didn't test https://github.com/Jigsaw-Code/outline-client/pull/42 properly. `setsystemproxy.exe` depends on `cygwin.dll`. If it isn't present in the same folder, connection fails. Since `ss-local.exe` also depends on it, just place all three in the same folder.
Also, update the comments so that this doesn't happen again :-)

place executables in the same folder, now they both depend on cygwin.dll

---

bower.json
package.json
www/app/app.ts
yarn.lock

ShadowsocksConfig does not send the access key as with errors as of v0.0.7, so there is no longer the need to strip it.

Update ShadowsocksConfig to v0.0.8

---

www/app/app.ts
www/app/cordova_main.ts
www/app/electron_main.ts
www/app/main.ts
www/app/platform.ts
www/messages/en.json
www/messages/es.json
www/ui_components/servers-view.html

This removes the "this is not a full VPN" warning from the Windows client. This leaves `user-comms-dialog.html` unused currently but I think that will change in future.

remove the non-system VPN warning

---

package.json

Apologies, forgot to do this as part of:
https://github.com/Jigsaw-Code/outline-client/pull/105
(merging TBR)

bump version for windows release

---

config.xml
cordova-plugin-outline/android/java/org/outline/vpn/VpnConnectionStore.java
cordova-plugin-outline/android/java/org/outline/vpn/VpnTunnelService.java
cordova-plugin-outline/plugin.xml

* Adds support for Always On VPN.
* Enables the auto-connect feature: automatically connects the VPN, unconditionally if the user has enabled Always On, or if the VPN was connected at shutdown. The latter behavior targets Lollipop and Marshmallow users, as Always On was introduced in Nougat.
* Does not perform connectivity checks when connecting at startup to avoid networking errors if the network is not ready.
* Persists the connection status to support both Always On and auto-connect - part of this code was already merged but not enabled.

Android: enable auto-connect feature, always-on

---

apple/xcode/osx/Outline/Classes/AppDelegate.m
cordova-plugin-outline/apple/src/OutlineVpn.swift
cordova-plugin-outline/apple/vpn/OutlineConnectionStore.swift
cordova-plugin-outline/apple/vpn/PacketTunnelProvider.m
cordova-plugin-outline/apple/vpn/Shadowsocks.h
cordova-plugin-outline/apple/vpn/Shadowsocks.m

* Enables the auto-connect feature for iOS and macOS. 
* Configures the VPN to connect on demand to any available network, allowing the VPN to automatically connect on boot if it was connected at shutdown.
* Enables the macOS launcher application to start the app's UI.
* The VPN can no longer be managed through Settings/System Preferences.
* Bypasses the connectivity checks for auto-connect.

Apple auto-connect

---

gulpfile.js

* We were generating RTL CSS after transpilation using the source HTML files in `www`. This broke the UI in WebViews that do not support ES6.
* This change uses the transpiled HTML in the platform directory as source to generate RTL CSS.
* Fixes #93.

Generate RTL CSS using transpiled ES5 as source

---

config.xml
cordova-plugin-outline/plugin.xml
gulpfile.js
package.json
yarn.lock

This fixes a build incompatibility with recent versions of
the Android SDK.  It also enables some new features of
cordova-android, like Java 8 support.

Upgrade cordova-android from 5.2.2 to 7.1.0

---

config.xml
www/app/app.ts
www/ui_components/add-server-view.html

This should help in case users get confused about what to do with
an invite.  On Android it can also bypass S3 entirely.
This also fixes a bug with the existing intent filter on Android, which doesn't seem to be getting added to AndroidManifest.xml.
See https://github.com/Jigsaw-Code/outline-website/pull/86 and https://github.com/Jigsaw-Code/outline-server/pull/185.

Accept our S3 invite URLs directly

---

config.xml

Fixes URL interception for `ss://` links in Android.

Use single intent filter for URL interception

---

.travis.yml
package.json
yarn.lock

Seems like the Windows build has been failing on Travis because the Docker image moved to Node 10 and a couple of our dependencies weren't ready. I think we may as well just move to Node 10.

move to node 10, fix windows build on travis

---

electron/custom_install_steps.nsh

Looks like this isn't necessary now the installer runs as admin.

no need to prompt for openvpn trust now installer runs as admin

---

electron/process_manager.ts

Two things here:
- I figured out a way to detect successful `ss-local-exe` launches, to improve our Sentry reports.
- Without an `on('error')` handler `spawn` was raising an uncaught exception which could cause PII to be included in Sentry reports.
Also some code formatting updates throughout the file; happy to revert those if you find it distracting.

tweak ss-local launch on windows

---

cordova-plugin-outline/outlinePlugin.js
electron/index.ts
package.json
www/app/app.ts
www/app/electron_main.ts
www/app/fake_connection.ts
www/app/i18n.ts
www/app/main.ts
www/app/outline_server.ts
www/app/util.ts
www/app/windows_connection.ts
www/model/errors.ts
www/types/electron-promise-ipc.d.ts
www/types/outlinePlugin.d.ts
yarn.lock

This introduces the idea of "regular" and "red flag" plugin exceptions. As discussed, the latter trigger a Sentry report. For now, there's just two "red flag" errors:
- could not start `ss-local.exe`
- could not modify the routing table
Both are Windows-specific. The first may be overkill, depending on how we decide to deal with virus checker-type software; I hope the second gives us a better idea of what kind of routing tables are out there.
The way I've implemented this, a Sentry report will now also be triggered for any other unexpected exceptions on connect/disconnect. I believe this is how Sentry is intended to be used :-)
I tackled this by diving into the code from `app.ts#connectServer` down and couldn't resist a few other bits and bobs along the way:
- `connectServer` and …

categorise plugin errors as regular/irregular, automatically report irregular

---

electron/routing_service.ts
www/types/sudo-prompt.d.ts

Had a report that I suspect is due to the user not having admin permissions but I can't be sure because sudo-prompt error reporting is currently broken. This addresses that, simplifies the call chain a bit (my bad, I was lazy last time I was in here), and removes the timeout - @alalamav I didn't see any evidence that it was necessary, can you remember the exact story?

fix sudo-prompt error reporting, simplify call chain

---

www/app/app.ts

Hmm, uncaught error reporting seems to work on Linux - where I sometimes test/develop changes to the Windows client - but not on Windows. This seems to work much better than relying on the uncaught exception.
This should be the final PR before 1.2.5.

report red flag errors via sentry explicitly

---

cordova-plugin-outline/android/java/org/outline/shadowsocks/ShadowsocksConnectivity.java
cordova-plugin-outline/android/java/org/outline/vpn/VpnTunnelService.java

* Prevents Sentry from filtering messages due to sensitive word scrubbing.
* Only affects the Android client.

Replace 'credentials' in log messages

---

electron/process_manager.ts
www/app/url_interceptor.ts
www/app/util.ts

* Removes logging from interceptor.
* Does not log promise objects in `util.timeoutPromise`.

Remove logging

---

electron/custom_install_steps.nsh
electron/install_windows_service.bat

* Fixes the routing service installation script to properly communicate exit codes.
* Aborts installation when the service installation fails.
* Uninstalls the routing service.
(Credit to @trevj for spotting the bugs ⭐️🥇)

Windows installer improvements

---

README.md
config.xml

The Play Store requires that existing apps target version 26 or higher by November 1st 2018.

Update Android target version to 26

---

third_party/badvpn/tun2socks/tun2socks.c

* This is not an issue in production since we haven't updated tun2socks for Android since making changes for Windows.
* Prevents the Android client from sending DNS queries through both transparent DNS and SOCKS UDP.

Prevent Android client from sending duplicate DNS queries

---

electron/build_action.sh
electron/custom_install_steps.nsh
electron/install_windows_service.bat
electron/routing_service.ts

_Sorry, this took longer than expected due to a faulty machine..._
This makes the client **reinstall and restart** OutlineService when it encounters a pipe error (currently it just restarts).
I refactored `install_windows_service.bat` into a "bounce the service" script, used by both installer and client.
Obviously, this should really just be the installer's job but by doing this in the client we'll get - in addition to helping those users with connection problems - much more debugging info.
Also do this for `EPIPE` errors, which have been showing up quite a bit.

have the client restart the service when there is a pipe error

---

cordova-plugin-outline/android/java/org/outline/vpn/VpnTunnelService.java

More accurately reports the VPN's network capabilities by marking the VPN as using the current active network. This is [particularly relevant](https://developer.android.com/about/versions/pie/android-9.0-changes-all#network-capabilities-vpn) in Android 9.
Addresses #265.

Set the VPN's underlying network

---

electron/add_tap_device.bat
electron/custom_install_steps.nsh
electron/package_action.sh
electron/release_action.sh

This should help us figure out why the TAP device won't install on some machines: submit a Sentry event each time the install fails, using basically the same approach as the server installer. Turns out NSIS includes a simple HTTP client so this wasn't as hard as I figured (initially I looked at `curl` but the Windows version is 1.5MB compressed!).
Each event includes:
- the output from `add_tap_device.bat`
- Windows version
- client version
Lots of NSIS trial and error but it seems to work on Win 7, 8, and 10.

automatically report TAP device installation failures

---

resources/master_messages.json
www/app/app.ts

Displays a different message (antivirus) for Windows than other clients when Shadowsocks fails to start.

Fix Shadowsocks start failure messaging

---

electron/index.ts

Adding servers via URL interception was broken in the Windows client because the system adds a trailing slash to the URL. Strip the slash before sending it to the UI.

Fix Windows URL interception

---

cordova-plugin-outline/android/java/org/outline/vpn/VpnServiceStarter.java
cordova-plugin-outline/android/java/org/outline/vpn/VpnTunnelService.java

* We're still seeing `RemoteServiceExceptions` because the VPN service exits early, without calling `startForeground` if there wasn't a connection at shutdown when started on boot.
* Moves the auto-start logic to `VpnServiceStarter` so it only starts the service if there was an active connection at shutdown
* Follow-up to #280.

Android: start the service on boot only if there was an active connection at shutdown

---

electron/custom_install_steps.nsh

Turns out when UAC is set really low - as it was in the VM I tested with - it basically doesn't work at all: either it launches as the current user without prompting or it prompts but won't recognise a admin account username/password. Weird. I see many reports on the internet about this, at least for Windows 7.
This adds a check and makes the installer quit.

quit installer when not running as admin, to handle uac failures

---

src/electron/add_tap_device.bat
src/electron/custom_install_steps.nsh

Still trying to nail down TAP device installation errors; main thing is to try to stamp out empty breadcrumbs since we get no debugging in that case:
- fix comment regarding stdout/stderr
- add a bunch of breadcrumbs to `add_tap_device.bat` (partially for easier debugging, mostly to help identify cases where breadcrumbs totally fail to send - now, there should always be output from `add_tap_device.bat`)
- escape double-quotes, so that we get breadcrumbs when there is a " in `add_tap_device.bat` output (not sure if this ever happens but seems likely)
- use `-autosize` for when new device name is extra-long (it was being truncated)
- print the before and after device name list, to help debug Powershell errors (also, do not print the raw output to the user - it's not much use, this makes it …

a few things to aid TAP device debugging

---

third_party/badvpn/tun2socks/tun2socks.c

Just a small thing I noticed when trying to compile tun2socks for Linux: this label doesn't exist in this function. Guess I missed this while getting compilation to work on Windows:
https://github.com/Jigsaw-Code/outline-client/pull/96

fix tun2socks compilation on linux

---

src/electron/custom_install_steps.nsh

Still seeing TAP device install failures with no breadcrumbs, so two things:
- turns out `ExecToStack` returns the error code **or** "timeout" **or**, if the command didn't launch, "error" - add this status to error reports
- provide an explicit path to `cmd.exe` in case on some systems a batch file can't be invoked directly (seems to mostly affect Win 7/8)

give explicit path to cmd.exe, add error status to sentry report

---

src/electron/add_tap_device.bat

A little followup to https://github.com/Jigsaw-Code/outline-client/pull/327, made possible by the input coming into Powershell already stripped of empty lines. Also replace `like '%%'` with `is not null`, for clarity (IMO).
@clementhk FYI (and thanks again)

simplify powershell expression, now blank lines are stripped out

---

src/www/ui_components/server-card.html

see #136 for more info
before:
after:

fix #136 (add word-break for long server names)

---

src/www/app/app.ts

* The webintent Cordova plugin intercepts referrer intents, broadcast when the app is installed from the Play Store.
* Not ignoring them causes the referrer extra to get interpreted as an `ss` URL and to display an 'invalid access key' error message. 
* Check that intercepted URLs start with `ss://` or are invite links.
FYI @sandrigo.

Ignore intercepted Play Store referrer intent by checking URL protocol

---

cordova-plugin-outline/android/resources/bypass_subnets.xml

* Android Lollipop (API 21-22) fails to establish a connection when adding the `224.0.0.0/4` route. 
* There should be no side-effects of removing this subnet, since these are [host group addresses](https://tools.ietf.org/html/rfc1112#section-4) used for multicasting.

Android: remove bypass subnet to allow connections in Lollipop

---

cordova-plugin-outline/apple/vpn/PacketTunnelProvider.m

Until we understand how this feature is causing connectivity issues as described in #352.

Apple: roll back LAN bypass

---

cordova-plugin-outline/android/java/org/outline/vpn/VpnTunnel.java
cordova-plugin-outline/android/java/org/outline/vpn/VpnTunnelService.java

* When a VPN is established, `connectivityManager.getActiveNetworkInfo()`, returns the underlying network set by the VPN. 
* Use the network passed to `onAvailable` to set the underlying network instead of the active network, and do not perform a comparison between them.
* This change properly sets the VPN's underlying network for Android API 23+, meaning that apps that require WiFi connectivity now work correctly with the VPN.
* Tested that network changes are still handled on Android API <23.

Improve logic to handle new available networks

---

src/electron/add_tap_device.bat

I see quite a few failures due to `wmic` varying the width output in the before and after cases; this runs trim() on the wmic files, fixing the issue. Also, fix a typo.

fix for varying column widths in wmic output

---

src/electron/add_tap_device.bat
src/electron/custom_install_steps.nsh

Motivated by:
https://github.com/Jigsaw-Code/outline-client/pull/341
Two benefits of this change:
- Outlinen will occupy (slightly) less space on disk when installed
- `tapinstall.exe` will appear in the same location on disk for 32 and 64 bit users, potentially making rescue and manual intervention instructions easier

remove parameter to add_tap_device.bat, only install files for the system's architecture

---

apple/xcode/ios/Outline/Outline-Info.plist
apple/xcode/ios/Outline/VpnExtension-Info.plist
apple/xcode/osx/Outline/Outline-Info.plist
apple/xcode/osx/Outline/VpnExtension-Info.plist
cordova-plugin-outline/apple/vpn/PacketTunnelProvider.m
cordova-plugin-outline/apple/vpn/Subnet.swift

* Re-enables LAN bypass without excluding '0.0.0.0/8' route.
* A beta build of the iOS client has been in TestFlight for a week, without any reported problems.
* Tested both clients locally.
* Increases the build numbers for App Store submission.

Apple: re-enable LAN bypass, increase versions

---

src/electron/add_tap_device.bat

A new issue in 1.2.18, installation is failing on Windows 7 in certain cases because `.trim()` can't be found. It didn't make much sense to me at first but my guess is that because `get-content`/`cat` returns an array, `.trim()` "magically" works on Win 8/10 due to some automatic type conversion - but not always on Windows 7. This PR trims each line one by one.
Followup to:
https://github.com/Jigsaw-Code/outline-client/pull/360

more explicit trim, for older versions of windows

---

cordova-plugin-outline/apple/vpn/PacketTunnelProvider.m

We don't have translations yet, but this is a first l10n step.

Apple: replace native hardcoded strings with NSLocalizedString

---

src/www/app/app.ts
src/www/ui_components/add-server-view.html

* When the app is invoked via URL interception (`ss://` protocol handler) the passed server information is parsed. But as soon as the received information is shown, the clipboard is parsed as well and if it contains Outline server information, the clipboard data will overwrite the latest server information.
* This PR fixes this race and does not allow for clipboard data to override the server import from URL interception.

Fix race between URL interception and clipboard server import

---

tools/OutlineService/OutlineService/OutlineService.cs

This in advance of some additions to the service to fix DNS leaks.
I did two things in Visual Studio:
- organise imports
- format document (ctrl-k, ctrl-d)
I realise the braces are *not* Google's regular style but since we're not regular VS coders, I figure it's better to go with its defaults.
BTW, clang-format does not support C#.

apply Visual Studio formatting to OutlineService.cs

---

src/electron/add_tap_device.bat

The perils of fixing near-unreproducible issues. Why pick a guessable name when you could be different to literally every other scripting language ever made?
Followup to:
https://github.com/Jigsaw-Code/outline-client/pull/387

batch files do not sleep

---

config.xml

* Cordova Android v7.1.2 introduced a bug that prevents cordova-plugin-outline from being installed.
* This issue has been fixed in v7.1.3.
* See [cordova-android/#542](https://github.com/apache/cordova-android/pull/542) for more details.
* Update to v7.1.4 - latest npm version.

Update Android Cordova to v7.1.4

---

src/electron/add_tap_device.bat

(finally, i hope)
* change `netsh interface show interface name=xxx` to `netsh interface ip show interfaces | find "%DEVICE_NAME%"` because ` netsh interface show interface name=xxx` doesn't have delay
* increase timeout
* fix check for error level

fix netsh wait

---

cordova-plugin-outline/apple/vpn/PacketTunnelProvider.m

* Selects a semi-random IP address from a pool of private subnets by checking it against the network interface subnets in order to decrease the probability of a collision.
* Sets the remote server's address as the VPN's server IP - previously we used a private LAN address.
* Does not affect routing, the system only uses this address to display it in `Settings > VPN > Outline`.
* Note that the TUN device's (virtual) IP address cannot be set to localhost.
* See the [documentation](https://developer.apple.com/documentation/networkextension/neipv4settings/1406709-initwithaddresses?language=objc) for more details.

Apple: assign an unused IP address to the VPN

---

package.json
yarn.lock

We finally ran into this:
https://github.com/Jigsaw-Code/outline-client/issues/377
The real fix, I think, is to move to Gulp 4 but, judging from having quickly tried it here, that will require some changes to our Gulpfile.
Fixes broken Travis:
https://travis-ci.org/Jigsaw-Code/outline-client/jobs/466707582

workaround broken build in node 10.10.14.2

---

gulpfile.js

Currently if `tsc` fails while the app is building, the build stops but the reason is not shown. We then need to run `tsc` separately to find out what went wrong.
~To help developers, this change will display the error from `tsc` whenever it fails. If `tsc` succeeds, it will display nothing (as it does now).~
----
An alternative solution would be to always display all of `tsc`s output, [as seen here](https://stackoverflow.com/a/31104898/99777). ~Let me know if you would prefer that approach.~ It has the advantage of being a one-liner. ✅ ✅ ✅ 👍
~But one advantage of the approach here: We could make the output even clearer by adding `process.exit()` instead of throwing the error. That would display only the relevant `tsc` error, and not gulp's noisy error, which is somewhat distracting for …

If tsc fails during the build, display its error

---

src/electron/add_tap_device.bat

When the client detects that the TAP device is absent or misconfigured it asks the user to reinstall Outline; however, the reinstaller doesn't actually try to reconfigure the TAP device. This makes the installer re-configure the TAP device if it already exists. Should help a few users.

reconfigure TAP device on reinstall

---

.travis.yml

This will pull in the auto-update files, too (currently missing from https://github.com/Jigsaw-Code/outline-client/releases/tag/linux-v1.0.2, damn).

travis is not uploading auto-update files

---

config.xml

Several little things have gone into master since 1.2.8 so I'd prefer roll a whole new release, from master.

bump version numbers for android 1.2.9

---

src/electron/index.ts

Once https://github.com/Jigsaw-Code/outline-client/pull/494 is merged, the window icon is the last user of `__dirname` which I'd like to replace throughout with `app.getAppPath()` - but it turns out there's no need to specify a window icon at all because if unspecified the app's icon will be used:
https://electronjs.org/docs/api/browser-window

no need to specify browserwindow icon

---

src/electron/index.ts
src/www/app/outline_server.ts
src/www/app/windows_connection.ts

Bah, https://github.com/Jigsaw-Code/outline-client/pull/497 broke connection error reporting: apparently `electron-promise-ipc` now serialises exceptions, so the conversion in `windows_connection.ts` was wrong.

fix connection error reporting due to change in electron-promise-ipc

---

src/electron/process_manager.ts

We removed this notifcation in https://github.com/Jigsaw-Code/outline-client/pull/481 - can you remember why? It's preventing the system tray from being updated on disconnection.

fix system tray icon status on disconnection

---

tools/build/Dockerfile
tools/build/build.sh

Bah, our Android build has been failing on Travis for a few days:
- last successful daily: https://github.com/Jigsaw-Code/outline-client/releases/tag/daily-2019-01-17
- first Travis failure: https://travis-ci.org/Jigsaw-Code/outline-client/jobs/485176565
The issue is that the Android SDK thinks we haven't accepted the license terms. I don't know exactly how this works (it must check the timestamp on `/opt/android-sdk/licenses/android-sdk-license` or something) but re-building the image seems to fix it. I also updated and culled a few deps - the image is a little smaller now.
One big thing to tackle soon is that `yarn gulp build` doesn't return a non-zero status when the script fails - wut!?

re-generate the Android Docker image, to fix broken CB

---

gulpfile.js
package.json
yarn.lock

The steps to make the web app "Cordova compatible" are intermixed with the Cordova build/prepare commands and operate on the files in `platforms/` rather than `www/`. This significantly complicates the Gulpfile. This PR moves them together, in anticipation of breaking them out to another build target altogether...basically, I'm chipping away at this file.

co-locate steps to make web app cordova-compatible

---

gulpfile.js
package.json
yarn.lock

Should make it easier to slowly gut this file. Also Gulp should actually return with non-zero now if any step fails (spotted in https://github.com/Jigsaw-Code/outline-client/pull/512).
I verified this produces exactly the same web app; tested the built app on Android and macOS.

detangle our Gulpfile, move to Gulp 4.x

---

gulpfile.js

* cordova-ios < 5.0.0 fails to compile the project via command line after moving to Xcode 10.
* This workaround preserves the compatibility between cordova-ios < 5.0.0 and  Xcode 10 until we upgrade to cordova-ios@5.0.0 (which requires cordova 8).
* Note that builds from the Xcode project are not affected by this change and were working since updating to Xcode 10.

Fix iOS build with workaround for Xcode 10/cordova-ios compatibility

---

src/electron/add_tap_device.bat

Accidentally discovered the cause of some weird Sentry reports: if the TAP device has been disabled (conceivable if someone has had trouble installing Outline and tried to fix it manually) then the device cannot be configured (setting subnet, etc., fails).
So, (re-)enable the TAP device during install. Should help a few users out.

(re-)enable the TAP device during install

---

src/electron/index.ts

This is bad: if there's a stored connection (from the last shutdown) then Outline doesn't create a windowand you have to kill the process and restart before it will do so. Reported here, I was finally able to reproduce when working on https://github.com/Jigsaw-Code/outline-client/pull/535:
https://github.com/Jigsaw-Code/outline-client/issues/501
Very simple fix, just verified it on my VM.

fix for no window on startup when no stored connection

---

gulpfile.js

* Transpiles and generates RTL CSS from the same directory (`www`). 
* RTL CSS was clobbering transpilation because we were generating RTL CSS from un-traspiled sources.
* Fixes #541.

Transpile JS and generate RTL CSS from the same source

---

src/electron/routing_service.ts

Virtually the only unexpected connection error I'm seeing so far with https://github.com/Jigsaw-Code/outline-client/pull/555 at 20% is that the routing daemon is not running. I forgot to throw the correct error. Also, clarify the other "connection time" error thrown by this class.

show reinstall message when routing daemon cannot be reached

---

src/electron/process_manager.ts

* Disables tun2socks DNS caching via arguments for Windows and Linux.

Electron: disable tun2socks DNS cache

---

src/electron/index.ts

This accomplishes two goals
First, and directly, it helps us roll out upgrades faster.
Secondly, this is the first step towards getting a better understanding of the scale of use of Outline.  The second step will be to release our binaries on S3 instead of the outline-releases repo, giving us the ability to use their anonymized and aggregated Request Metrics.

Check for updates every 6 hours

---

cordova-plugin-outline/android/java/build-extras.gradle

* Due to a bug in Cordova, the values for minimum and target SDK versions declared in config.xml are not taking effect in the built APK. As a result the minimum SDK version was set to 19, which is not supported.
* Overrides the versions through a custom Gradle build file.
* Verified that the built APK SDK versions expected though `aapt` and `apkanalyzer`.

Android: set minimum sdk version to 21

---

src/electron/routing_service.ts

* Handles routing service responses (JSON) parsing failiures to prevent the error from propagating to the user.
* Logs failures so we can fix the underlying problem (as reported on Linux #633) through feedback submissions.
* Fixes restarting the routing service (daemon) by attaching socket error/close listeners after the connection has been established. Enables the routing service restart behavior in Windows.

Routing service improvements

---

apple/xcode/ios/Outline/Outline-Info.plist
apple/xcode/ios/Outline/VpnExtension-Info.plist
apple/xcode/osx/Outline/Outline-Info.plist
apple/xcode/osx/Outline/VpnExtension-Info.plist

* Increases the iOS and macOS clients app version and build numbers.
* Note that this release is intentionally at the same commit as `[ios|macos]-v.1.3.1. We are updating the app store description, which requires a release. This is not at the tip of `alalama-go-tun2socks` to prevent releasing a half-completed migration to the Go network stack - preventing us from shipping two copies of Shadowsocks libraries (libev & Go).

Release Apple clients v1.3.2

---

src/electron/release_linux_action.sh
src/electron/release_windows_action.sh

This corresponds with https://github.com/Jigsaw-Code/outline-releases/pull/133.  See there for rationale
We will need to merge both, then cut a release of the client, then wait for requests to client/foo to go to zero before stopping publishing to both locations.

Pull updates from per-platform directories

---

package.json
src/www/model/events.ts
yarn.lock

A parameter of type `(interface {}) => void` can't take a function of type
`(interface {param: some_type}) => void` as an argument.  I'm not sure why,
this seems like a bug in Typescript's type system, but this seems common
enough that I'd expect there's an explanation.
Luckily, all `OutlineEvent`s take `server: Server` as a parameter.  This creates
the issue, however, that we are trying to get the constructor of an
interface which only says it has a Server parameter -- not a constructor
which takes it.  So we create a `ServerConstructible `interface specifying
types which take Servers as parameters and have them publicly available,
and then get its constructor through `Object.getPrototypeOf()`
This error occurs on more recent versions of typescript than we were using.  This PR also …

Fix type mismatches in OutlineEvent.

---

apple/xcode/ios/Outline.xcodeproj/project.pbxproj
apple/xcode/ios/Outline/Outline-Info.plist
apple/xcode/ios/Outline/VpnExtension-Info.plist
apple/xcode/osx/Outline.xcodeproj/project.pbxproj
config.xml
cordova-plugin-outline/android/scripts/copy_third_party.js

* Note that the latest Android build number in production is 28.
* Fixes an Android build issue by creating a missing `libs` directory,.
* Fixes an Apple failure to strip symbols from the tun2socks framework by not embedding it. This seems to be an issue with Go/gomobile: https://github.com/golang/go/issues/28997.

Increase versions, build fixes for mobile beta release

---

README.md

rsync isn't installed by default by the Cygwin installer, so make a note that this needs to be selected by the user.

Add note to Windows section

---

apple/fastlane/Gemfile
apple/scripts/install_fastlane.sh
gulpfile.js

* Fixes iOS packaging on Travis by only generating the Xcode project instead of attempting to build it. Currently this step fails because provisioning has not been configured through fastlane. 
* Updates fastlane to v2.140.0.

iOS: fix remote packaging

---

src/www/ui_components/server-card.html

Fixes a bug in newer iOS webviews, where UI elements stay highlighted after user interaction.

Remove outline (CSS) from focused server card UI elements

---

src/electron/add_tap_device.bat
src/electron/custom_install_steps.nsh
src/electron/find_tap_device_name.bat

- Migrates the TAP device name detection to a batch script following reports that the Go binaries fail to run on some environments.
- Waits for the TAP device to be visible to `netsh` after installing it and after renaming it. `netsh` not recognizing the adapter has been the leading cause of TAP install failures.

Migrate TAP device name detection to batch

---

package.json

We don't want prettier to override tslint for TS files.

Only lint HTML files with prettier

---

README.md
config.xml
scripts/environment_json.sh
src/electron/custom_install_steps.nsh
src/electron/package_windows_action.sh
src/electron/release_windows_action.sh
src/www/app/cordova_main.ts
src/www/app/electron_main.ts
src/www/app/environment.ts

- Removes development and production Sentry API keys from the repository.
- Removes the now deprecated native Sentry DSN.
- Enables error reporting through a `SENTRY_DSN` environment variable.
- Added a new production Sentry API key to Travis in order to start deprecating the old keys.

Remove Sentry API keys

---

apple/xcode/ios/Outline/Outline-Info.plist

Outline stubbornly stays in portrait mode on an iPad, resulting in having to tilt one's head 90 degrees like a quizzical poodle when using an iPad with an attached keyboard. This change supports Landscape mode on iPad devices only.

Introduce support for landscape on iPads

---

src/electron/add_tap_device.bat
src/electron/custom_install_steps.nsh

* Defines error codes for `add_tap_device.bat`.
* Surfaces error codes  to the user (in the existing dialog) and in Sentry error reports (as the title).
* Users will be able to contact support with more detailed information about the failure.
* Sentry error reports will be grouped by error code, easing the overhead of determining error rates.

Windows: surface TAP install error codes to user and sentry

---

config.xml

* Enables landscape and portrait orientations, which is the Cordova default for Android.
* Follow up to #778.

Android: enable all orientations

---

src/electron/index.ts

- Fixes #781 by only initializing sentry in the Electron main process when the DSN is defined.
- The failure happens when the environment variable `SENTRY_DSN` is undefined - affecting development.

Electron: init sentry only when DSN is defined

---

tools/build/build.sh

- Fixes release builds on the Android Docker image by making `SENTRY_DSN` available to the image.

Export SENTRY_DSN to Android build Docker image

---

.travis.yml

- Currently, this branch fails to deploy releases on non-beta builds because `BETA=$([[ $TRAVIS_TAG == *"beta"* ]] && echo '--beta')` exits with 1.

Fix non-beta builds on Travis

---

src/www/app/electron_main.ts
src/www/app/error_reporter.ts

Don't init sentry if we don't have a DSN for it.
Continuation of #794, to fix #781
----
I could have introduced a boolean `gotSentry` to each class, so they can skip calling `sentry.captureEvent()` or `sentry.captureMessage()` if sentry was not initialised.
However it seems in electron at least this isn't necessary. Calls to `captureEvent()` appear to do nothing when sentry was not initialised.
I hope the same is true for Cordova (which calls multiple sentry functions) but I didn't test it.
But should you want a `gotSentry: true/false` implementation, I do have that code stashed.

Electron: init sentry only when DSN is defined cont.

---

src/www/ui_components/server-card.html
src/www/ui_components/server-connection-viz.html
src/www/ui_components/server-list.html
src/www/ui_components/servers-view.html

* Condenses the server card UI when there are more than one server.
* Implements a responsive server list, with a threshold of 360px screen width.
* The UI remains unchanged if there are no servers (intro screen) or one server (full size single server card).
* [Demo video](https://drive.google.com/file/d/1cWrxUGm1m9zWQZQHq9-VbpMl-ZDivnzM/view?usp=sharing).

Reduce server card size when there are multiple servers

---

src/www/ui_components/server-connection-viz.html

- Currently, there is a bug in the connection animation ripple effect due to the ripple height not being responsive.
- Experimented with making the ripple height responsive, but the ripple effect looks messy in smaller displays that have multiple servers.
- Opted for removing the ripple effect from the connection animation.
- Demos
- [Single server](https://drive.google.com/file/d/1cJnKX-ZfIuczsxSLZJ1EDTwl-68nE2Uf/view?usp=sharing)
- [Multiple servers](https://drive.google.com/file/d/1E2zhKr6QXwMqRlWIaiXI8HjT8pc_2tpb/view?usp=sharing)

Remove connection animation ripple effect

---

src/www/app/app.ts
src/www/ui_components/app-root.html

- Previously, we set the app version directly on the about UI element. However, it seems like the property is not propagating to Polymer. As a result, the app version is not displayed in the about view.
- Fixes this issue by setting the app version on the root view and binding that property to the about view.

Fix app version not displaying

---

config.xml

- Android v1.4.0 has not been relased, but v1.4.0 (32) was uploaded to the Play Store.
- Increases the Android version code to 33 in order to upload and release v1.4.0 (master), including the app version display fix in #836.

Increase Android version code

---

tools/build/Dockerfile
tools/build/build.sh

- Updates the Docker image used for building the Android client.
- Replaces the deprecated SDK tools with command line tools.
- Updates the Android build tools to v30.0.2.
- Sets `ANDROID_SDK_ROOT` env var instead of the deprecated `ANDROID_HOME` env var.
- The image `quay.io/outline/build-android:2020-09-10` has been uploaded to [quay.io](https://quay.io/repository/outline/build-android?tab=tags).
- Tested that the Android client builds and runs successfully via CI after this change.

Update android build docker image

---

tools/build/Dockerfile
tools/build/build.sh

- Installs NDK v21.0.6113669, side by side to Android build tools v30.0.2, on the Android build docker image.
- Updates the Android build docker image.

Install NDK (side by side) in Android docker build image

---

apple/xcode/ios/Outline/Outline-Info.plist
apple/xcode/ios/Outline/VpnExtension-Info.plist
third_party/go-tun2socks/METADATA

- Downgrades the go-tun2socks iOS framework to v2.0.0 due to a significant increase in memory usage.
- outline-go-tun2socks v2.1.* depends on Go 1.14, which seems to be the cause of the baseline memory increase: ~11MB vs ~9MB device idle on v2.0.0.
- Does not roll back go-tun2socks for other platforms, since we haven't observed increased crash rates and iOS has a strict 15MB memory limit on the VPN process.
- Bumps the iOS minor version to account for the cordova-ios (WKWebview) update.
cc @fortuna

iOS: downgrade go-tun2socks to v2.0.0

---

package.json
src/types/ambient/outlinePlugin.d.ts
src/www/app/app.ts
src/www/app/cordova_main.ts
src/www/app/electron_main.ts
src/www/app/electron_outline_tunnel.ts
src/www/app/fake_tunnel.ts
src/www/app/main.ts
src/www/app/outline_server.ts
yarn.lock

- Replaces promise chains with async/await syntax.
- Catches previously uncaught promise rejections and stops throwing in `main`.

Use async/await

---

tools/outline_proxy_controller/Dockerfile
tools/outline_proxy_controller/outline_controller_server.cpp
tools/outline_proxy_controller/outline_controller_server.h
tools/outline_proxy_controller/outline_proxy_controller.h

This updates the build from Ubuntu Cosmic (which is no longer available)
to Ubuntu Focal (supported until 2025).  This required removing use of
deprecated Boost API calls.
This PR also changes the default DNS server to better match the behavior of
other Outline clients.

Update Outline Proxy Controller docker build

---

cordova-plugin-outline/android/java/org/outline/vpn/VpnTunnel.java
src/electron/add_tap_device.bat

- Adds Cloudflare and Quad9 DNS resolvers to the Windows and Android clients (Apple and Linux clients' resolvers have been updated).
- Removes DYN resolvers since we have observed issues with DNS/TCP.

Update Android and Windows DNS resolvers

---

src/electron/index.ts
src/electron/process_manager.ts
src/electron/routing_service.ts
src/electron/tunnel_store.ts
src/types/ambient/outlinePlugin.d.ts
src/www/app/cordova_main.ts
src/www/app/electron_main.ts
src/www/app/electron_outline_tunnel.ts
src/www/app/fake_tunnel.ts
src/www/app/outline_server.ts
src/www/app/persistent_server.ts
src/www/app/tunnel.ts
src/www/model/server.ts
src/www/model/shadowsocks.ts

- Moves the `cordova.plugins.outline.Tunnel` interface definition to typescript.
- Decouples the tunnel configuration (formerly `ServerConfig`) from the server model.
- Adds Shadowsocks model to define `ShadowsocksConfig`.
- Tested that the refactor did not affect functionality in any platform.

Define Tunnel interface in typescript

---

package.json
src/electron/index.ts
src/electron/process_manager.ts

We have had [a number of disconnection issues](https://github.com/orgs/Jigsaw-Code/projects/1?card_filter_query=label%3Afailure%2Fconnect) on both Linux and Windows.  This PR is a first step towards debugging by setting `ss-local` and `tun2socks` to verbose logging mode and redirecting their output to the electron process's stdout and stderr.
This PR was jointly authored by myself and @mpmcroy 
- Add verbose logging to ss-local and Tun2Socks
- Adds subprocess stdout/stderr logging through `console` so the logs appear in Sentry
Example Sentry logs from connecting and disconnecting from the VPN: https://sentry.io/organizations/outlinevpn/issues/2211797476/

Use verbose logging in ss-local and tun2socks when in Debug mode

---

package.json
yarn.lock

To match newly cut version https://github.com/Jigsaw-Code/outline-shadowsocksconfig/releases/tag/v0.1.2
This is to fix #774

bump ssconfig version number

---

src/electron/index.ts
src/electron/process_manager.ts

* Only logs from child processes in debug mode
* Logs exit codes or killing signals in prod mode
* Quiets BReactor logs
* Log disconnects and successful exit codes in `console.log` and error exits in `console.error`

Additional logging fixes

---

package.json
src/electron/index.ts
src/www/app/electron_main.ts
src/www/app/main.ts

Formerly it used the remote module to do this when `app.getName()` wasn't available (ie when not in the main process) but since Electron 10 the module has been removed by default in prep for its complete removal in Electron 14.
Tested: https://sentry.io/organizations/outlinevpn/issues/2211432007/?project=159503&query=is%3Aunresolved

Tell Sentry the app name from the renderer process

---

config.xml

Bumps the Android (minor) version to v1.5.0-go (35) for Play Store (beta channel) release.

Increase Android version

---

src/electron/index.ts
src/electron/tunnel_store.ts

With this change we only setup the auto launcher when needed (while the VPN is running).
This way we prevent leaving residue behind and unnecessary auto launches that may upset the user.
This also fixes the auto VPN start on Linux, which currently doesn't work because we only auto-start if `--autostart` is set, which doesn't happen on Linux. The app will auto-launch, but the VPN doesn't start!
Now we will auto start whenever there's tunnel information saved, fixing Linux.
I have no idea how to test this, since I wasn't able to get the networking working on my dev environment.

Cleanup and fix auto launch

---

src/electron/electron_main.webpack.js
src/electron/index.ts

- Since migrating the electron main process build to webpack, we are bundling @sentry/electron code for the main and renderer process. We get a runtime error on the main process because it attempts to import @senty/electron renderer process code when initializing the library.
- Fixes sentry initialization by directly importing @sentry/electron main process code.
- See [sentry-electron/#142](https://github.com/getsentry/sentry-electron/issues/142) and [related documentation](https://docs.sentry.io/platforms/javascript/guides/electron/#webpack-configuration). Note that we don't have to define the process type and import sentry conditionally, since we have separate webpack configurations for the main and renderer processes.

Fix @sentry/electron init on main process

---

src/electron/index.ts
src/www/app/electron_main.ts

- Fixes a runtime error initializing sentry on the Electron renderer process when debug mode is not set.
- Sends the app name to the renderer process unconditionally.
- Provides a fallback app name in the renderer process.

Electron: send app name regardless of debug mode

---

src/electron/go_vpn_tunnel.ts
src/electron/routing_service.ts
src/electron/sslibev_badvpn_tunnel.ts

Currently, a call to `Tunnel.disconnect()` shuts down all three helpers in
parallel, and the first one to close triggers another call to
`disconnect()` via `Promise.race(exits)`.  Both `disconnect()` calls try
to use `RoutingDaemon.socket.write()`.  If it has already closed, the second
call to `write()` will throw an exception that is surfaced to the user.

Fix race condition in RoutingDaemon.stop()

---

cordova-plugin-outline/android/java/org/outline/vpn/VpnTunnelService.java

Cherry-picks #992 on the `go-tun2socks` branch in order to release `android-v1.5.1` without the persistence layer changes in `master`.

Fix null pointer exception in VPN connectivity broadcast

---

src/www/app/electron_main.ts
src/www/app/error_reporter.ts
src/www/app/outline_server.ts

-  Configures `sentry/browser` to only collect console events.
- Keeps the [default Sentry integrations](https://docs.sentry.io/platforms/javascript/configuration/integrations/default/) with default options.

Configure sentry to only collect console statements

---

cordova-plugin-outline/apple/src/OutlinePlugin.swift

- Stops collecting device timezone and memory stats.
- Fixes a build error due to a typo in #991.

Apple: don't collect device timezone and memory

---

config.xml
cordova-plugin-outline/README.md
cordova-plugin-outline/android/aidl/org/outline/IVpnTunnelService.aidl
cordova-plugin-outline/android/java/build-extras.gradle
cordova-plugin-outline/android/java/org/outline/OutlinePlugin.java
cordova-plugin-outline/android/java/org/outline/vpn/VpnTunnel.java
cordova-plugin-outline/android/java/org/outline/vpn/VpnTunnelService.java
cordova-plugin-outline/android/scripts/copy_third_party.js
cordova-plugin-outline/plugin.xml

- Merges the Android client Go network stack from the [go-tun2socks](https://github.com/Jigsaw-Code/outline-client/tree/go-tun2socks) feature branch at ca0f04b.
- Deprecates shadowsocks-libev and badvpn-tun2socks for Android.
- Connectivity checks are also migrated to Go (VPN service process).
- Starting from v1.5.0, the Android clients has been released from the go-tun2socks branch.
- All code in this PR has been reviewed before merging into the go-tun2socks branch (i.e. #664, #670).
- Updates the cordova-plugin-oultine documentation.

Migrate Android network stack to Go

---

cordova-plugin-outline/android/java/org/outline/log/SentryErrorReporter.java
cordova-plugin-outline/android/java/org/outline/vpn/VpnTunnelService.java

- Now that the VPN service runs in a separate process and is automatically restarted on crashes, we are seeing an increase of native (JNI/Go) Sentry error reports.
- Sets a sample rate for the VPN service process error reports in order to reduce the volume of automatic crash reports.
- Does not affect user feedback reports, or error reports in the main app process.

Android: sample VPN process error reports

---

scripts/do_action.sh
scripts/l10n/import_native_android_strings_action.sh
scripts/test_action.sh
third_party/shadowsocks-libev/linux_action.sh
tools/find_tap_name/build_action.sh

I have a bit of a wacky file system setup where my folders contain strange characters - spaces and parentheses, etc. In order to support building the client on my machine, I had to wrap all instances of `$ROOT_DIR` and vars derived from `$ROOT_DIR` in double quotes to escape these characters. Doing so I am now able to run `do_action.sh` successfully.

add quotes to $ROOT_DIR in case of bad chars

---

apple/xcode/osx/Outline.xcodeproj/project.pbxproj
apple/xcode/osx/Outline/Outline-Info.plist
apple/xcode/osx/Outline/VpnExtension-Info.plist
src/www/ui_components/app-root.js

- Removes the quit button from the macOS client app.
- Builds the macos app only for x86_64 - Xcode 12.5 builds all architecures (including arm64) by default.
- Bumps the macos client bundle version.

macOS release updates

---

.github/workflows/build_and_test.yml
tools/build/build.sh

This is a continuation of @JonathanDCohen's previous work. It individually builds clients for Linux, Windows, MacOS and Android in the CI. We need to set up fastlane w/ GH actions to support iOS.
<details>
<summary>TODOs:</summary>
</details>

CI build for Linux, Windows, MacOS and Android

---

src/www/app/app.ts
src/www/ui_components/add-server-view.js

When user pastes or types an invalid access key in the "Add server dialog", the dialog will be dismissed without any notifications; nothing changed on the main UI either. So our users are pretty confused and do not know what's going on.
This is because we will **always** close the dialog to show the "server already added" notification. However this notification will only be popped up when the exception matches `errors.ServerAlreadyAdded`. For other types of exception, although we had an error message "invalid access key" in the dialog, the dialog itself is dismissed regardless of the exception type.
So the fix is pretty simple, only dismiss the dialog when exception is `errors.ServerAlreadyAdded`.
P.S., also fixed two related boolean attribute usage.
Fixes #1063 .

🐛 fix(ui): ensure the error message is displayed when access key is invalid

---

src/www/electron.webpack.js

According to the [webpack v4 docs](https://v4.webpack.js.org/plugins/ignore-plugin/), `webpack.IgnorePlugin(/Regex/);` is equivalent to `new webpack.IgnorePlugin({resourceRegExp: /Regex/});`. This is, however, not the case. It seems we must now specify the context regexp as well.

fix(electron): add contextRegExp to webpack.IgnorePlugin

---

src/electron/build.action.sh

In this change set, I replaced the [old `libev` network stack](https://github.com/Jigsaw-Code/outline-client/tree/master/third_party/badvpn) with the unified [`go` network stack](https://github.com/Jigsaw-Code/outline-go-tun2socks).
I have already tested the client on both Windows and Linux, they all work as expected. But we are still required to install the TAP device as well as the daemon service on both OSes.
Add @daniellacosse for awareness, we can have a dry run of the Linux CI pipeline to release this version.
Completes one step in #1128 .

build(netstack): enable go network stack for Windows and Linux

---

src/www/ui_components/server_card.ts

We did not observe the correct property (we were using `serverId` instead of `serverName`), therefore when we rename a server card, the new name will not be applied immediately, it will only be applied after restart.
In this fix, I simply reference the correct `serverName` property so the new name will be refreshed as soon as we update a server name.
Fixes #1131 .

fix(ui): refresh new server name after renaming

---

README.md

We modified the [build script](https://github.com/Jigsaw-Code/outline-client/pull/1172#issue-840507797) before. In this PR, I updated the corresponding documentation.

docs: update electron build instructions

---

scripts/get_electron_build_flags.mjs

This PR fixes an issue caused by mismatching argument when cross-building Windows electron app on macOS. The platform argument passed to `get_electron_build_flags.mjs` should be `windows` instead of `win`.

👷 build(windows): pass the correct electron-builder argument for Windows

---

.github/workflows/build_release_candidates.yml
.github/workflows/build_windows_release_candidate.yml
README.md

In this PR, I introduced the Windows release pipeline (to build _unsigned_ release candidate binaries). The pipeline can be:
* Either triggered manually
* Or automatically triggered by the overall Release Candidate mega-pipeline
Following is the manual triggered workflow image:

👷 build(windows): introduce Windows release pipeline

---

.github/workflows/build_release_candidates.yml

Note: I didn't test this, but I'm pretty sure it will work. It'll be faster to fork if something goes wrong after we merge.

feat(release): copy current iOS CI process over to the build_release_candidates workflow

---

scripts/get_version.mjs

We fixed [a critical issue related to electron and cordova](https://github.com/Jigsaw-Code/outline-client/pull/1238) several days ago. Although we did not observe any serious outcomes for Windows app, it is still possible that there might be some issues hidden below.
Therefore, here I will release a new version 1.7.1 for Windows.

🔖 release(version): bump up Windows to 1.7.1 for the electron cordova fix

---

src/electron/index.ts
src/electron/routing_service.ts

Previously when user clicks the "CONNECT" button, but encounters some errors (for example, routing daemon service is not running), our app still thinks we have *connected*, which is wrong. Even worse, when user tries to "DISCONNECT" then, our app just freezes forever.
In this PR, I fixed this issue by always making sure the `onceDisconnected` event is fired in `RoutingDaemon` when `stop()` method is called. It will then trigger the `onceDisconnected` event in `ShadowsocksLibevBadvpnTunnel`, and reset the state.

💊 fix(electron): fix wrong connection status when error is thrown during connect

---

scripts/run_action.mjs
src/electron/build.action.sh
src/www/views/servers_view/server_card/index.ts

- adds missing width to single server indicator
- updates webpack flag script name
- don't show letter head on every bash script run

fix(www): missing indicator width

---

src/cordova/setup.action.mjs

Reverts Jigsaw-Code/outline-client#1318
This breaks `www/start`. We need to find a better way of doing it.

fix(devtools): revert 'remove plugins folder on cordova setup'

---

src/electron/electron-builder.json
src/electron/index.ts

Our app's icon is not shown in Ubuntu Dock (on Windows it is fine):
Similar issues are reported to electron-builder (e.g., https://github.com/electron-userland/electron-builder/issues/2269). Though the issue is declared to be "fixed", it is actually not, people are still using the workaround of setting main windows's icon in electron code.
In this fix, I use the workaround mentioned above which is to forcibly set the window icon to the 64x64 icon image. The following images illustrate the icon displayed under 100%, 150% and 200% dpi settings:
I did not set the icon to 128x128 because it actually looks too sharp under the regular DPI setting (100%), here a comparison between 64x64 and 128x128 under 100% dpi (though in higher dpi's, the 128x128 looks better):

fix(electron/linux): 💊 outline icon is not shown in Ubuntu Dock

---

src/www/views/servers_view/server_list_item/server_card/index.ts

forgot to add prefixed text select on the relevant fields for ios...

fix: restore text selection on iOS

---

src/www/ui_components/app-root.js
src/www/views/servers_view/index.ts

fix(www): 💊 hide server list scroll bar when there is enough space

---

src/www/views/servers_view/server_list_item/server_card/index.ts

With long text without spaces, the container expanded and the button went beyond it.
Added max width for text block.

fix: wrap long words in server name

---

commitlint.config.js
tools/outline_proxy_controller/outline_proxy_controller.cpp
tools/outline_proxy_controller/outline_proxy_controller.h

> Please refer to the internal Issue ID: 239705916
> Test with Outline Client v1.7.0
In this PR, I implemented a `safe-popen` to replace the original `popen` system call.
I also refactored the `queue<pair<string, string>>` based `SubCommand` to a `vector<string>` based `CommandArguments` because:
1. We made assumptions about shell context, for example, we had code `SubCommand.push({"add dev", "xxx"})` which will be expanded to three arguments `add dev xxx`. This will not work in new code because `add dev` will be treated as a single argument. We can either split the string by spaces, or we just refactored it to a `vector`, I chose the later one.
2. It makes more sense to use a list of items than a FIFO queue as **argument list**
Finally I removed the un-implemented `createRoutingString` …

fix(service/linux): 🔒️ prevent command injection issue

---

commitlint.config.js
src/electron/add_tap_device.bat
tools/outline_proxy_controller/outline_proxy_controller.cpp

In this PR, I narrow down the subnet size of our tun/tap device to a single host (previously it was a `/24` subnet). Although I have tested with the current client and it is working, it would still be better to replace [the `255.255.255.0` network mask](https://github.com/Jigsaw-Code/outline-client/blob/1d2826339d8253f58f09281a2ae2a8385a5da715/src/electron/sslibev_badvpn_tunnel.ts#L38) used in `ss-local`. Let's use another PR to resolve this issue because:
1. For backward compatibility, because in Linux we do not have a way to upgrade the service for now
2. We will switch to the [go network stack](https://github.com/Jigsaw-Code/outline-client/blob/1d2826339d8253f58f09281a2ae2a8385a5da715/src/electron/go_vpn_tunnel.ts#L35) soon
Now the new tun/tap configuration looks like:
**Windows** …

fix(service): 🔒️ reduce tun device subnet size to one (/32)

---

tools/outline_proxy_controller/outline_proxy_controller.h

In this PR, I updated `ip` and `sysctl` command to absolute paths: `/usr/sbin/ip` and `/usr/sbin/sysctl`. This will prevent any potential pollution to the `PATH` environment variable.
From the screenshot below it is confirmed that the strings in the binaries are updated:

fix(service/linux): 🔒️ use absolute path for binaries to prevent PATH pollution

---

resources/original_messages.json
src/electron/routing_service.ts
src/www/messages/en.json
tools/outline_proxy_controller/dist/install_linux_service.sh
tools/outline_proxy_controller/dist/outline_proxy_controller.service
tools/outline_proxy_controller/outline_controller_server.cpp
tools/outline_proxy_controller/outline_controller_server.h
tools/outline_proxy_controller/outline_daemon.cpp

In this PR, I updated the permission model of the "outline_proxy_controller" daemon. We will have a group named as `outlinevpn`, only users in this group will be able to access "outline_proxy_controller" (through UNIX socket `/var/run/outline_controller`). During installation, we will only add the current user to `outlinevpn` group. System admins are free to add more users into this group. The new permission is listed below:
```
srw-rw---- 1 junyi outlinevpn 0 Oct  4 21:09 /var/run/outline_controller
```
Notice that I updated the owner to the current user `junyi` (instead of the default `root`), this is to prevent any potential restarts because Linux won't refresh group membership within the same login session.
Also I replaced all shell commands to absolute paths to prevent any potential …

feat(service/linux): 🔒️ add outlinevpn group to further restrict permissions

---

src/www/app/app.ts

On Windows, `localize` is not initialized in the following call stack:
- `this.syncServersToUI()`
- `this.makeServerListItem()`
- `this.getServerDisplayName`
- `this.localize(server.isOutlineServer ... )`

fix(www): 💊 `localize` is not initialized during `syncServersToUI`

---

config.xml

This is in the docs... I just forgot about it because Apple manages this for you automatically.

chore: update android build number to 41

---

src/electron/go_vpn_tunnel.ts
src/electron/process.ts

In this PR, I refactored `ChildProcessHelper` to use the async model when launching new child process, to replace the old event model. So the caller can get out the exit code more easily. As a side effect of this refactoring, I used `ChildProcessHelper` to implement the `checkConnectivity` feature in `GoVpnTunnel`, I also fixed #1449 by reading the exit code from `ChildProcessHelper`.

refactor(electron): ♻️ use async model for ChildProcessHelper

---

config.xml
src/build/get_version.mjs
src/cordova/apple/xcode/ios/Outline/Outline-Info.plist
src/cordova/apple/xcode/ios/Outline/VpnExtension-Info.plist
src/cordova/apple/xcode/macos/Outline/Outline-Info.plist
src/cordova/apple/xcode/macos/Outline/VpnExtension-Info.plist

This pull request bumps up the version number of all platforms to prepare for the version 1.7.0 release:
* Android v1.8.1
* iOS v1.8.1 (with VpnExtension v1.8.1)
* macOS v1.8.1 (with VpnExtension v1.8.1)
* Windows/Linux v1.8.1

chore: 🎉 release v1.8.1 for all platforms

---

tools/outline_proxy_controller/CMakeLists.txt
tools/outline_proxy_controller/Dockerfile
tools/outline_proxy_controller/logger.cpp
tools/outline_proxy_controller/logger.h
tools/outline_proxy_controller/outline_controller_server.cpp
tools/outline_proxy_controller/outline_controller_server.h
tools/outline_proxy_controller/outline_daemon.cpp
tools/outline_proxy_controller/outline_proxy_controller.cpp

I this PR, I upgraded several dependencies used by Linux service in order to use [C++20's coroutine](https://en.cppreference.com/w/cpp/language/coroutines), which is easier to understand than the legacy boost coroutine, also it will enable more features (like cancellation, multiple listeners) more easily.
* Upgrade `libboost` from `1.67` to `1.80`
* Upgrade `g++` from `9` to `10` (didn't upgrade to `11` or `12` for backward compatibility)
* Refactor the legacy boost coroutine with the new C++20 coroutine
* Some style refactoring according to [Google C++ Style Guide](https://google.github.io/styleguide/cppguide.html)
* Statically links standard C++ library to support more OS versions

refactor(service/linux): ♻️ upgrade boost and gcc to use co_await

---

docs/apple_development.md
third_party/CocoaLumberjack/Makefile
third_party/sentry-cocoa/Makefile

Use `bootstrap` instead of `update`. The `update` command will prevent reproducible builds.

chore(build): fix Carthage call

---

package-lock.json
package.json
src/build/get_version.mjs

This PR fixes a critical issue caused by out-dated `tun2socks.exe`.
I also downgraded `electron` to `19` due to a [breaking change introduced in `electron 20`](https://www.electronjs.org/docs/latest/tutorial/tutorial-preload#augmenting-the-renderer-with-a-preload-script): we are not allowed to use the `os` package in even preload script any more.

fix(electron/windows): 💊 use the latest go-tun2socks

---

src/cordova/apple/OutlineAppleLib/Package.swift
src/cordova/apple/xcode/ios/Outline/Outline-Info.plist
src/cordova/apple/xcode/ios/Outline/VpnExtension-Info.plist
src/cordova/apple/xcode/macos/Outline/Outline-Info.plist
src/cordova/apple/xcode/macos/Outline/VpnExtension-Info.plist
src/cordova/build.action.mjs

In this PR, I fixed the Android release script, and synced `BundleVersion` from Apple's App Store back to this repository. In addition, due to [a bug in golang's compiler for iOS](https://github.com/golang/go/issues/58323), I rebuilt the `outline-go-tun2socks` binary and updated the checksum here.

fix: 🔨 fix Android release script and update Apple bundle versions

---

src/electron/go_vpn_tunnel.ts

The checkConnectivity method didn't check for salt prefixes, so the connection would never get established in countries where Outline doesn't work without a salt prefix.

fix(electron): added salt prefix to check connectivity

---

src/build/get_version.mjs

This hotfix fixes the connectivity test when prefix is applied: #1599

chore: 🚀 release v1.10.1 for Windows and Linux

---

src/electron/build_main.action.mjs
src/electron/index.ts
src/electron/preload.ts
src/electron/start.action.mjs
src/www/app/electron_main.ts
src/www/ui_components/app-root.js

Previously Sentry is working in electron apps because:
* [`webpack_electron_main.mjs`](https://github.com/Jigsaw-Code/outline-client/blob/644dc7761bf9c246720eb97ecf59ce1077ed2d92/src/electron/webpack_electron_main.mjs#L23) is accepting an object with field `appVersion`, but we are [passing `APP_VERSION` to it](https://github.com/Jigsaw-Code/outline-client/blob/644dc7761bf9c246720eb97ecf59ce1077ed2d92/src/electron/build_main.action.mjs#L37). Therefore we are skipping the [Sentry initialization in main process](https://github.com/Jigsaw-Code/outline-client/blob/644dc7761bf9c246720eb97ecf59ce1077ed2d92/src/electron/index.ts#L85) because the global variable `APP_VERSION` is `undefined`.
* We did not `import '@sentry/electron/preload'` (different than `Sentry.init`) to initialize Sentry …

fix(electron): 💊 initialize Sentry in main, preload and renderer

---

.gitattributes

By default, GitHub excludes `build/` folders from [some searches](https://support.github.com/ticket/personal/0/1954062), such as the `t` search on GItHub's website. This makes sense in many projects.
However, Outline's `/*/build/` folders contain scripts, not build artefacts (which in Outline appear under `/output/` - although formerly `/build/`)
This change will allow github to search Outline's `build/` folders, as with most other folders.
(Docs on `linguist` attributes [here](https://github.com/github-linguist/linguist/blob/master/docs/overrides.md).)
To test:
- On the [repo's GitHub page](https://github.com/JigSaw-Code/outline-client/), press `t` and then try a search for `download_file`. You will get 0 results.
- Try the same on [this PR's …

chore: allow GitHub to search build folders

---

src/cordova/apple/xcode/macos/Outline.xcodeproj/project.pbxproj

I was able to get it working with a release build.
This should address https://github.com/Jigsaw-Code/outline-client/issues/940

feat(cordova/apple): re-enable Apple Silicon builds

---

src/cordova/android/README.md
src/cordova/plugin/android/scripts/copy_third_party.js

fix(build): 💊 make Android build script cross platform

---

src/electron/README.md
src/electron/add_tap_device.bat
src/electron/custom_install_steps.nsh
src/electron/install_windows_service.bat

This PR tries to prevent the local privilege escalation issue in Outline Client Windows installer by specifying the full path of system commands. Note that in a `.bat` file we can use `%SystemRoot%` variable (typically expands to "C:\Windows"), but it is not available in the `.nsh` NSIS script, therefore we need to use the [NSIS defined constant `$SYSDIR`](https://documentation.help/CTRE-NSIS/Section4.2.html#4.2.3) (typically expands to "C:\Windows\System32").
I also removed the Cygwin related information from the document because it is not required any more.
Fixes: b/266050099

fix(electron/windows): 🩹 prevent command LPE in the installer

---

.github/ISSUE_TEMPLATE/support_request.md

Clarify that only SDK developers should use the SDK board board.

chore: update support_request.md

---

.github/ISSUE_TEMPLATE/question.md

Clarify that only SDK developers should use the SDK board board.

chore: update question.md

---

src/www/ui_components/app-root.js
src/www/views/contact_view/index.spec.ts
src/www/views/contact_view/index.ts

Currently, the state remains even if the user clicks the back button, which is managed by the parent `AppRoot` element. This means that if they were sent to a help center article and then open the contact view in a subsequent navigation, they can't get to the original wizard to get help for a new issue.

fix(www): reset the contact view if the user navigates back

---

src/www/app/app.ts

Nodes created dynamically (e.g. inside a `dom-if` template) are not added to the `this.$` hash.

fix(www): use `querySelector` now that element is dynamically created

---

src/www/ui_components/app-root.js
src/www/views/contact_view/index.spec.ts
src/www/views/contact_view/index.ts
src/www/views/contact_view/stories.ts

feat(www): polish the contact view UI

---

src/electron/connectivity.ts
src/electron/index.ts

This PR reverts part of the changes in #1663 , which is critical to domain name keys.
This helps address the issue #1760

fix(electron): 🩹 fix connection issue of domain name keys

---

src/cordova/apple/xcode/ios/Outline/Outline.entitlements
src/cordova/apple/xcode/ios/Outline/VpnExtension.entitlements

The location of the logs directory is specified by the provided App Group ID. This needs to match the app group so the `VpnExtension` can write log files for Sentry.

fix(cordova/apple/macos): correct app groups for catalyst

---

src/electron/install_windows_service.bat

Double quote the path of `OutlineService.exe` in Windows service installation script to prevent a potential vulnerability discovered by a user's internal scanner below; in addition, this will also allow us to [add arguments to the service command](https://stackoverflow.com/a/11084834) in the future.
Unquoted Search Path or Element is vulnerable:
- https://cwe.mitre.org/data/definitions/428.html
- https://isc.sans.edu/diary/Help+eliminate+unquoted+path+vulnerabilities/14464
- http://www.ryanandjeffshow.com/blog/2013/04/11/powershell-fixing-unquoted-service-paths-complete/

fix(client/electron/windows): double quote full path of OutlineService

---

resources/original_messages.json

See https://github.com/Jigsaw-Code/outline-apps/pull/1921#discussion_r1516840689

chore(www): fix `END_OF_LINK` placeholders

---

resources/original_messages.json

#1924 updated the placeholders of an existing message, without changing the message ID. This is a problem in the Translation Console as it can mess up existing translations that are based on a single placeholder. Here I'm changing the message ID by adding the `meaning` attribute, as suggested.

chore(www): add `meaning` attribute to messages with updated placeholders

---

package-lock.json
package.json
src/infrastructure/electron/app_paths.ts
src/tun2socks/build.action.mjs

This PR fixes a `node-gyp` build error of Outline Client for Windows by upgrading it to the latest version.
And the `tun2socks` not found runtime error caused by the wrong path of the file.

fix(build): fix Outline Client build in Windows

---

client/resources/original_messages.json

This was never properly added to the translation workflow, which means it gets deleted by our translation exporter. This should add it to the pipeline.

fix(www): add alternative access key message to the translation pipeline

---

.gitattributes

This fixes #1988 .
(I guess I will need to renormalize the line endings once it's getting merged?)

fix(client/electron/windows): force `eol=crlf` for Windows installation scripts

---

client/infrastructure/electron/app_paths.ts
src/electron/electron-builder.json
src/electron/go_vpn_tunnel.ts
src/electron/routing_service.ts

This PR fixes several path issues in electron caused by the recent source code movement and output path change in #1967 .

fix(client/electron): update electron's tun2socks paths built by taskfile

---

server_manager/messages/master_messages.json
server_manager/web_app/ui_components/outline-support-form.ts

This breaks the translation console pipeline, as it generates a message with the same ID but with different descriptions.

fix(manager): remove duplicate message

---

.github/workflows/build_and_test_debug_client.yml
client/src/tun2socks/outline/connectivity/connectivity_test.go

This PR fixed "`fakeSSClient` does not implement `StreamDialer`" compilation error in `connectivity_test.go`.
I also added Go test to the CI workflow so we can catch similar errors in the future.

test(client): fix failed tun2socks connectivity_test cases

---

client/electron/go_vpn_tunnel.ts
client/electron/index.ts
client/electron/preload.ts
client/electron/process.ts
client/src/tun2socks/outline/electron/main.go
client/src/tun2socks/outline/platerrors/doc.go
client/src/tun2socks/outline/platerrors/error_code.go
client/src/tun2socks/outline/platerrors/marshal.go
client/src/tun2socks/outline/platerrors/marshal_test.go
client/src/tun2socks/outline/platerrors/platform_error.go
client/src/tun2socks/outline/platerrors/platform_error_test.go
client/src/tun2socks/outline/shadowsocks/client.go
client/src/tun2socks/outline/shadowsocks/config.go
client/src/www/app/app.ts
client/src/www/app/electron_outline_tunnel.ts
client/src/www/app/error_code_localizer.ts
client/src/www/app/error_localizer.ts
client/src/www/app/outline_server_repository/server.ts
client/src/www/model/errors.ts
client/src/www/model/platform_error.ts
infrastructure/timeout_promise.ts

Added detailed error propagation from Golang to TypeScript for the desktop Outline Client (Windows & Linux).
**Empty hostname**
**Port out-of-range**
**Empty hostname**
**Port out-of-range**

feat(client/electron): propagate structured errors from Go to TypeScript

---

.github/workflows/build_and_test_debug_manager.yml

From the [official "About GitHub-hosted runners" document](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories):
> The macos-11 label has been deprecated and will no longer be available after 28 June 2024.
I replaced it with `macos-13` to align with the [Client runner](https://github.com/Jigsaw-Code/outline-apps/blob/af91355e9e7fc9a20af3cd0aced9593129b050ad/.github/workflows/build_and_test_debug_client.yml#L121), and removed the `xcode-select` command since [XCode 13 is not supported by GitHub actions](https://github.com/actions/runner-images/blob/main/images/macos/macos-13-Readme.md#xcode) any more.
This unblocks #2044 .

ci(manager/mac): use `macos-13` as the CI runner

---

client/src/cordova/android/README.md

- Updated Android development environment setup steps
- Adjusted paths to reflect the new repository folder structure
- Removed oudated content (e.g., the scripts in `tools/` folder, as they no longer exist)

docs(client/cordova/android): update paths and remove outdated info

---

package-lock.json
package.json

Chalk is used by src/build. It needs to be in the root package.json.

build: add missing dependency

---

client/src/cordova/android/OutlineAndroidLib/outline/src/main/aidl/org/outline/IVpnTunnelService.aidl
client/src/cordova/android/OutlineAndroidLib/outline/src/main/java/org/outline/vpn/VpnTunnelService.java
client/src/cordova/plugin/android/java/org/outline/OutlinePlugin.java
client/src/tun2socks/outline/shadowsocks/client.go

The logic has already been removed in #1663 , this PR cleans up the dead code for Android.

refactor(client/cordova/android): remove dead reachability test code

---

client/electron/index.ts

This is due to a bug in removing trailing slash that removes all of the slashes of the URL.
For example:
`ssconf://cool.url.com/a/b/c` would become `ssconf://cool.url.comabc` which effectively breaks the dynamic server config URL.
This issue needs to be fixed since it broke the functionality of ssconf:// links entered from browser.
Changed `substr` to `substring` since `substr` was deprecated.

fix(client/electron): `/` are incorrectly removed in `ssconf://` links

---

client/src/cordova/android/OutlineAndroidLib/outline/src/main/aidl/org/outline/IVpnTunnelService.aidl
client/src/cordova/android/OutlineAndroidLib/outline/src/main/aidl/org/outline/TunnelConfig.aidl
client/src/cordova/android/OutlineAndroidLib/outline/src/main/java/org/outline/vpn/VpnTunnelService.java
client/src/cordova/plugin/android/java/org/outline/OutlinePlugin.java
client/src/cordova/plugin/apple/src/OutlinePlugin.swift
client/src/www/app/outline_server_repository/vpn.cordova.ts

This cleans up TunnelConfig on Android, passing the transport as an opaque string.
On Apple, we complete the migration by sending a string from Typescript.
/cc @62w71st

chore(client): pass transport as string on Android and Apple

---

client/resources/original_messages.json
client/src/www/views/root_view/add_access_key_dialog/index.ts

This breaks the l10n build. We could probably disambiguate with a meaning attribute, but it's easier to just re-use the same message as we use "Cancel" for dialogs across many other places.
Changing "Confirm" to also be more generic so it can be re-used.

chore(client): remove duplicate "Cancel" message

---

client/electron/go_vpn_tunnel.ts
client/electron/process.ts
client/go/outline/electron/main.go

Refactored the electron client to leverage the new exported Outline Go API for checking server connectivity and creating the client instance.
Additionally, modified the connectivity test to output both `TCPErrorJson` and `UDPErrorJson` to `stdout` instead of exiting with a specific error code.
**Connectivity test outputs (stdout, exit code = 0)**
- No errors:
```
[tun2socks] - checking connectivity ...
{"tcp":"","udp":""}
```
- UDP not supported:
```
[tun2socks] - checking connectivity ...
{"tcp":"","udp":"{\"code\":\"ERR_PROXY_SERVER_UDP_NOT_SUPPORTED\",\"message\":\"UDP connectivity check timed out\"}"}
```
- Server unreachable:
```
[tun2socks] - checking connectivity ...
{"tcp":"{\"code\":\"ERR_PROXY_SERVER_UNREACHABLE\",\"message\":\"failed to dial to the …
```

refactor(client): use new Go API for electron

---

client/electron/electron-builder.json

This commit reverts the product name from "outline-client" back to "Outline".
This also fixed the reinstallation issue. Though I'm still not sure about the root cause, it could be that electron-builder failed to handle the '-' character (similar to https://github.com/electron-userland/electron-builder/issues/6488, but not exactly the same).

fix(client/windows): restore product name to "Outline"

---

client/electron/app_paths.ts
client/electron/preload.ts
client/electron/routing_service.ts
client/src/www/app/app.ts
client/src/www/app/main.electron.ts
client/src/www/model/platform_error.ts

New initialization confirmation dialog:

fix(client/linux): use new installation error and service path

---

.github/workflows/pull_request_checks.yml

Reverting the upgrade since it breaks our scopes that uses `/`.

ci(devtools): fix PR commitlint workflow

---

client/src/www/views/root_view/root_header/index.ts

* Updated `h1` styles in the root view to prevent the logo text from being selectable

fix(client): disable selectability of logo text

---

client/src/cordova/apple/xcode/ios/Outline.xcodeproj/project.pbxproj

This platform filter was accidentally removed in #2090 and causing asset validation issues for the iOS app:
```
Asset validation failed
This bundle is invalid. Applications built for more than one architecture require an iOS Deployment Target of 3.0 or later. (ID: ec5bf398-a85e-4069-a03f-9b7cb51b40c4)
Asset validation failed
Unsupported Architectures. The executable for Outline.app/Frameworks/AppKitIntegration.framework contains unsupported architectures '[x86_64]'. (ID: 72745965-6014-4983-9631-028f7a57c917)
Asset validation failed
Invalid bundle structure. The “Outline.app/Frameworks/AppKitIntegration.framework/Versions/A/AppKitIntegration” binary file is not permitted. Your app cannot contain standalone executables or libraries, other than a valid CFBundleExecutable of supported …
```

fix(client/ios): filter `AppKitIntegration` framework to `maccatalyst`

---

client/electron/index.ts
client/src/www/app/app.ts
client/src/www/app/outline_server_repository/config.spec.ts
client/src/www/app/outline_server_repository/config.ts
client/src/www/app/outline_server_repository/index.ts
client/src/www/app/outline_server_repository/outline_server_repository.spec.ts
client/src/www/app/outline_server_repository/server.ts
client/src/www/app/outline_server_repository/vpn.fake.ts

This PR further reduces the exposed surface of the config library and the dependency of config-specific details, advancing the goal to be config agnostic and allow for new protocols, including Websocket. It follows https://github.com/Jigsaw-Code/outline-apps/pull/2265 and many other previous changes.
In this PR I introduce the concepts of Dynamic and Static `ServiceConfig`. The parsing function now returns the firstHop in the `TunnelConfigJson`.
I'm trying to minimize the number of functions we need to implement in Go. It's a huge pain to expose even a single function from Go, since it requires touching all platforms. Electron is particularly bad, as functions are implemented as binary execution in a new process.
I believe I've reached a point where I only need to implement …

refactor(client): reduce config library surface

---

.github/workflows/build_and_test_debug_manager.yml

This PR resolves the [sandbox error encountered during server manager web tests](https://github.com/Jigsaw-Code/outline-apps/actions/runs/12438976622/job/34995431528?pr=2291):
> `Cannot start ChromiumHeadless: No usable sandbox!`
This error is caused by [the more restricted unprivileged user namespaces feature](https://ubuntu.com/blog/ubuntu-23-10-restricted-unprivileged-user-namespaces) introduced in Ubuntu 23. It's a known limitation and many chromium based products (including electron) are affected by this change.
This PR switches the runner image from `ubuntu:latest` (which is Ubuntu 24) to `ubuntu:22.04`.

ci: fix Chromium sandbox issue of manager web test

---

.github/workflows/codeql.yml

This PR addresses the [inconsistent Node version issue in standard code scanning](https://github.com/Jigsaw-Code/outline-apps/actions/runs/12524028357/job/34934182362) by migrating to advanced code scanning according to [the official GitHub document](https://docs.github.com/en/code-security/code-scanning/creating-an-advanced-setup-for-code-scanning/configuring-advanced-setup-for-code-scanning).
I also added C# and Java to the code scanning configuration. Swift is not enabled due to errors, and we can investigate this in the future, as Swift was not enabled in the original configuration either.

ci: switch to advanced setup for code scanning

---

client/electron/go_helpers.ts
client/electron/go_vpn_tunnel.ts
client/electron/index.ts
client/electron/vpn_service.ts
client/src/cordova/plugin/apple/src/OutlinePlugin.swift
client/src/www/app/app.ts
client/src/www/app/main.cordova.ts
client/src/www/app/main.ts
client/src/www/app/outline_server_repository/config.spec.ts
client/src/www/app/outline_server_repository/config.ts
client/src/www/app/outline_server_repository/index.ts
client/src/www/app/outline_server_repository/outline_server_repository.spec.ts
client/src/www/app/outline_server_repository/server.ts
client/src/www/app/outline_server_repository/vpn.cordova.ts
client/src/www/app/outline_server_repository/vpn.fake.ts
client/src/www/model/server.ts
client/src/www/views/contact_view/support_form/index.spec.ts
client/src/www/views/root_view/add_access_key_dialog/index.ts
infrastructure/net.spec.ts
infrastructure/net.ts

This PR turns config parsing async, in preparation for parsing in the Go code. It had ripple effect all over the Typescript code.
This also changes the parsing API to output firstHop + transport, with transport being an opaque string as opposed to an object.

refactor(client): make parsing async and config an opaque string

---

client/electron/go_plugin.ts
client/electron/index.ts
client/electron/vpn_service.ts
client/src/www/app/main.cordova.ts
client/src/www/app/main.electron.ts
client/src/www/app/outline_server_repository/vpn.electron.ts

This ensures the error on invokeMethod is always parsed as a PlatformError.
This also moves StartProxying and StopPRoxying into the MethodChannel. We should not be introducing new IPCs and reuse the method channel instead.

chore(client): clean up invokeMethod error propagation

---

client/electron/vpn_service.ts
client/go/outline/vpn/vpn_linux.go

This fix allows the `AppImage` and `.deb` to work side-by-side. It also prepares to avoid IP conflicts with OpenVPN drivers for the new Windows routing.

fix(client/linux): update TUN and IP to avoid conflicts with legacy routing

---

client/go/outline/client.go
client/go/outline/client_test.go
client/go/outline/platerrors/platform_error.go
client/go/outline/platerrors/platform_error_test.go

This makes sure we won't accidentally allow proxyless.
Error:

fix(client): enforce no proxyless

---

client/go/outline/vpn/vpn.go

This PR adds a 10-second timeout to `CloseVPN()`.  The `CloseVPN()` method can hang a very long time if there's outgoing traffic and the network is unreachable, due to lwIP holding a global lock.
This is a workaround, so the user can quit the app. However, the lwIP lock *still* persist, requiring an **application restart**.

fix(client/linux): add timeout for CloseVPN

---

client/electron/build.action.mjs

This PR signs two dependent binaries included in the NSIS installer. These binaries are not tracked by Electron's build process (they are included by the NSIS builder instead). So we need to properly sign them by ourselves.

build(client/windows): code sign dependent binaries included in NSIS

---

client/go/outline/config/config_dial_endpoint.go
client/go/outline/config/parse.go
client/go/outline/parse.go
client/go/outline/parse_test.go
go.mod
go.sum

Fixes https://github.com/Jigsaw-Code/outline-apps/issues/2373
This also fixes another issue that went unnoticed before @khantzawhein raised it: our YAML parser was not correctly parsing escaped slashes. That was a [bug in go-yaml](https://github.com/go-yaml/yaml/issues/967). I fixed it by migrating our code to https://github.com/goccy/go-yaml.

fix(client): fix parsing of legacy JSON

---

.github/workflows/build_and_test_debug_client.yml
client/electron/README.md
client/electron/debian/after_install.sh
client/electron/electron-builder.json
client/electron/hooks/after_pack.cjs
client/electron/hooks/before_pack.cjs
client/tsconfig.json

Move `patchelf` RPATH patching from Debian installation time to build time.
This fixes an issue where the application would fail to install on systems without an up-to-date `patchelf` (for example, Ubuntu 18).

fix(client/linux): patch RPATH during build time rather than runtime

---

.github/workflows/build_and_test_debug_client.yml
client/go/Taskfile.yml

This PR targets the glibc version to `2.27`, it expands compatibility to OS as early as Ubuntu 18.

fix(client/linux): link with glibc 2.27 for wider compatibility

---

.github/workflows/build_and_test_debug_client.yml

The cache for the `setup-zig` action has been causing intermittent build failures. This change disables the cache to improve build reliability, trading off potential performance gains.

ci(client): disable cache for setup-zig action

---

client/src/www/views/root_view/root_navigation/index.ts
server_manager/www/ui_components/app-root.ts

Add open-in-new icons to sidebar links where opening in a new tab might be unexpected, on both the client and the server. Fixes https://github.com/Jigsaw-Code/outline-apps/issues/2348 (which has mysteriously disappeared, but was asking for indicators on external links).
Client:
- Added an icon to the 'Help', 'Privacy', 'Data collection' and 'Terms' links
Server:
- Added an icon to the 'Data Collection', 'Help', 'Privacy' and 'Terms' links

feat(client): add open-in-new icons to external links

---

commitlint.config.js

For any dependabot PRs we do want to merge, it uses this scope.

chore: allow `deps` as a commitlint scope

---

server_manager/install_scripts/install_server.sh

We shouldn't check for conflicting containers anymore. As of https://github.com/Jigsaw-Code/outline-server/pull/1494 we stop and remove shadowbox containers before we start new ones, so any error is now going to always find a conflicting container. This is likely what's happening in https://github.com/Jigsaw-Code/outline-server/issues/1650 and is obfuscating the real error.
This also resolves #2431.

fix(manager): do not check for shadowbox existence on errors

---

client/src/cordova/android/OutlineAndroidLib/outline/src/main/java/org/outline/vpn/VpnTunnel.java
client/src/cordova/android/OutlineAndroidLib/outline/src/main/java/org/outline/vpn/VpnTunnelService.java

This doesn't seem to be needed anymore, and just adds complexity.
To test, I ran on the emulator and checked the metered interfaces with and without the wifi while the VPN is on.
When only cell (metered) is on, we see both `eth0` and `tun1` being marked as metered:
```
% adb shell dumpsys netpolicy | head -8
System ready: true
Restrict background: false
Restrict power: false
Device idle: false
Restricted networking mode: false
Low Power Standby mode: false
Metered ifaces: {eth0, tun1}
```
The VPN inherits from the underlying default network.
If I turn on the Wifi, the `tun1` device no longer shows up as metered:
```
% adb shell dumpsys netpolicy | head -8 
System ready: true
Restrict background: false
Restrict power: false
Device idle: false
Restricted networking mode: false
Low Power …
```

chore(client): remove setUnderlyingNetwork and other minor cleanup

---

client/src/cordova/android/README.md

Instruct developers to make android tools available in their path. 
Later steps (`npx cordova requirements android`) require that `avdmanager` is available to call directly

docs(client/android): update android build README.md

---

client/src/www/app/app.ts

This PR fixes a bug where the server status was incorrectly displayed as `DISCONNECTED` instead of `CONNECTED` when a user added new servers or forgot existing ones.

fix(client): incorrect server status after adding/forgetting servers

---

client/electron/electron-builder.json
client/package.json
package-lock.json

This PR fixes the `Error: Cannot find the native Koffi module` on certain Linux systems.
The issue stemmed from Koffi 2.9.1 requires an executable stack (`execstack`). Some newer or security-focused systems (like Ubuntu 25 and Debian 13) disallow this, preventing the module from loading: `koffi.node: cannot enable executable stack as shared object requires: Invalid argument`.
So this PR upgrades Koffi to `v2.12.0` because [since `v2.10.0`, koffi no longer requires the executable stack (`-z noexecstack`)](https://koffi.dev/changelog#koffi-2-10-0).
Fixes #2491
Tested on: Debian Rodete

fix(client/linux): upgrade Koffi to resolve bundle issue

---

.github/scripts/android_setup_ci.sh
client/config.xml
client/package.json
client/src/cordova/android/OutlineAndroidLib/build.gradle
client/src/cordova/android/OutlineAndroidLib/outline/build.gradle
client/src/cordova/android/README.md
client/src/cordova/apple/xcode/macos/Outline/config.xml
package-lock.json

Updating:
- android API: 34 (14.0) -> 35 (15.0)
- cordova android: 13.0.0 -> 14.0.0 https://cordova.apache.org/docs/en/dev/guide/platforms/android/index.html (14.0.0 is considered `dev`)
- android gradle plugin: 8.3.0 -> 8.7.3
Tested:
Installed a build on my phone with adb and was able to connect through canary. (Also dark mode looks very nice!)

chore(client): upgrade android target api version to 35

---

client/go/configyaml/parse.go
client/go/outline/config/config_shadowsocks_test.go
client/go/outline/parse.go
client/go/outline/parse_test.go

This PR fixes https://github.com/Jigsaw-Code/outline-apps/issues/2576, where `\r` (carriage return) is not properly marshaled by the YAML library. We now use the standard library JSON marshaling instead (JSON is a subset of YAML).
Of note: `json.Marshal` preserves the case of the struct field names, while `yaml.Marshal` makes them lower-case. That's why we `json.Marshal` the map generated with `yaml.Unmarshal`.
I also added a lot more tests.

fix(client): fix config marshaling

---

client/electron/index.ts
client/electron/tunnel_store.ts
client/electron/vpn_service.ts
client/go/outline/vpn_linux.go
client/src/www/app/outline_server_repository/config.spec.ts
client/src/www/app/outline_server_repository/config.ts
client/src/www/app/outline_server_repository/server.ts
client/src/www/app/outline_server_repository/vpn.cordova.ts
client/src/www/app/outline_server_repository/vpn.fake.ts
client/src/www/app/outline_server_repository/vpn.ts
client/tsconfig.json

- Minimize use of `FirstHopAndTunnelConfigJson`
- Use `clientConfig` instead of `tunnelConfig`/`transportConfig` consistently.
- Stop using `config` as a field name. It's meaningless.
/cc @emohandesi @62w71st

chore(client): clean up client config

---

client/go/outline/config/types.go
client/go/outline/parse.go
client/go/outline/parse_test.go
client/web/app/outline_server_repository/config.spec.ts
client/web/app/outline_server_repository/config.ts

Return the ConnectionType back to typescript so we can differentiate various types of connections

feat: return the connection type in the tunnel config
